# Generated by Django 4.2.13 on 2026-07-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_fix_sequence_news_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author_name',
            field=models.CharField(blank=True, default='', help_text='Nama penulis berita', max_length=200),
        ),
    ]
