from django.urls import path
from .views import (
    WithdrawalListCreateView,
    WithdrawalSettingsView,
    WithdrawalServiceListView,
    JayapayInitiateView,
    JayapayCallbackView,
    JayapayPhPayoutInitiateView,
    JayapayPhPayoutCallbackView,
    JayapayPhPayoutBanksView,
    AtpayPayoutBanksView,
    AtpayPayoutInitiateView,
    AtpayPayoutCallbackView,
    AtpayPayoutQueryView,
    PPayProsPayoutInitiateView,
    PPayProsPayoutCallbackView,
    PPayProsPayoutQueryView,
    UsdPayoutInitiateView,
    UsdPayoutCallbackView,
    BankPayPayoutInitiateView,
    BankPayPayoutCallbackView,
    ReepayPayoutInitiateView,
    ReepayPayoutCallbackView,
    BatPayPayoutInitiateView,
    BatPayPayoutCallbackView,
    NextPayPayoutInitiateView,
    NextPayPayoutCallbackView,
    WithdrawalTransactionsListView,
)

urlpatterns = [
    path('', WithdrawalListCreateView.as_view(), name='withdrawal-list-create'),
    path('settings/', WithdrawalSettingsView.as_view(), name='withdrawal-settings'),
    path('services/', WithdrawalServiceListView.as_view(), name='withdrawal-services'),
    path('jayapay/initiate/<int:pk>/', JayapayInitiateView.as_view(), name='withdrawal-jayapay-initiate'),
    path('jayapay/callback/', JayapayCallbackView.as_view(), name='withdrawal-jayapay-callback'),
    path('jayapay-ph/banks/', JayapayPhPayoutBanksView.as_view(), name='withdrawal-jayapay-ph-banks'),
    path('atpay/banks/', AtpayPayoutBanksView.as_view(), name='withdrawal-atpay-banks'),
    path('jayapay-ph/initiate/<int:pk>/', JayapayPhPayoutInitiateView.as_view(), name='withdrawal-jayapay-ph-initiate'),
    path('jayapay-ph/callback/', JayapayPhPayoutCallbackView.as_view(), name='withdrawal-jayapay-ph-callback'),
    path('atpay/initiate/<int:pk>/', AtpayPayoutInitiateView.as_view(), name='withdrawal-atpay-initiate'),
    path('atpay/callback/', AtpayPayoutCallbackView.as_view(), name='withdrawal-atpay-callback'),
    path('atpay/query/<int:pk>/', AtpayPayoutQueryView.as_view(), name='withdrawal-atpay-query'),
    path('ppaypros/initiate/<int:pk>/', PPayProsPayoutInitiateView.as_view(), name='withdrawal-ppaypros-initiate'),
    path('ppaypros/callback/', PPayProsPayoutCallbackView.as_view(), name='withdrawal-ppaypros-callback'),
    path('ppaypros/query/<int:pk>/', PPayProsPayoutQueryView.as_view(), name='withdrawal-ppaypros-query'),
    path('usd-payout/initiate/<int:pk>/', UsdPayoutInitiateView.as_view(), name='withdrawal-usd-payout-initiate'),
    path('usd-payout/callback/', UsdPayoutCallbackView.as_view(), name='withdrawal-usd-payout-callback'),
    path('bankpay/initiate/<int:pk>/', BankPayPayoutInitiateView.as_view(), name='withdrawal-bankpay-initiate'),
    path('bankpay/callback/', BankPayPayoutCallbackView.as_view(), name='withdrawal-bankpay-callback'),
    path('reepay/initiate/<int:pk>/', ReepayPayoutInitiateView.as_view(), name='withdrawal-reepay-initiate'),
    path('reepay/callback/', ReepayPayoutCallbackView.as_view(), name='withdrawal-reepay-callback'),
    path('batpay/initiate/<int:pk>/', BatPayPayoutInitiateView.as_view(), name='withdrawal-batpay-initiate'),
    path('batpay/callback/', BatPayPayoutCallbackView.as_view(), name='withdrawal-batpay-callback'),
    path('nextpay/initiate/<int:pk>/', NextPayPayoutInitiateView.as_view(), name='withdrawal-nextpay-initiate'),
    path('nextpay/callback/', NextPayPayoutCallbackView.as_view(), name='withdrawal-nextpay-callback'),
    path('transactions/', WithdrawalTransactionsListView.as_view(), name='withdrawal-transactions'),
]
