# Generated by Django 4.2.13 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deposits", "0004_gatewaysettings_max_deposit_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatewaysettings",
            name="usd_gateway_api_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="gatewaysettings",
            name="usd_gateway_busi_code",
            field=models.CharField(
                blank=True,
                default="122002",
                help_text="Default busiCode (122002-122006)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gatewaysettings",
            name="usd_gateway_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gatewaysettings",
            name="usd_gateway_mer_no",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="gatewaysettings",
            name="usd_gateway_redirect_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="gatewaysettings",
            name="usd_gateway_sign_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Secret key untuk generate/verify signature",
                max_length=255,
            ),
        ),
    ]

