# Generated by Django 4.2.13 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deposits", "0005_usd_gateway_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("JAYAPAY", "Jayapay"),
                    ("KLIKPAY", "Klikpay"),
                    ("USD_GATEWAY", "USD Gateway"),
                ],
                max_length=20,
            ),
        ),
    ]

