# Generated by Django 4.2.13 on 2026-05-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0006_alter_deposit_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaysettings',
            name='usd_gateway_bank_code',
            field=models.CharField(blank=True, default='', help_text='Override bankCode/IP yang dikirim ke provider (kosong = pakai IP client dari request)', max_length=100),
        ),
    ]
