# Generated by Django 4.2.13 on 2026-05-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deposits", "0007_gatewaysettings_usd_gateway_bank_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatewaysettings",
            name="usd_gateway_max_deposit_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Maksimal nominal deposit USD (0 = tidak dibatasi)",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="gatewaysettings",
            name="usd_gateway_min_deposit_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Minimal nominal deposit USD (0 = tidak dibatasi)",
                max_digits=15,
            ),
        ),
    ]

