# Generated by Django 5.0.6 on 2026-05-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deposits", "0008_gatewaysettings_usd_deposit_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="amount_currency_code",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="deposit",
            name="credited_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="deposit",
            name="credited_currency_code",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]

