# Generated by Django 5.0.6 on 2026-05-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deposits", "0009_deposit_currency_amount_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatewaysettings",
            name="jayapay_ph_api_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="gatewaysettings",
            name="jayapay_ph_default_method",
            field=models.CharField(blank=True, default="GCASH", max_length=16),
        ),
        migrations.AddField(
            model_name="gatewaysettings",
            name="jayapay_ph_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gatewaysettings",
            name="jayapay_ph_mch_no",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="gatewaysettings",
            name="jayapay_ph_private_key",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Paste RSA PRIVATE KEY body ONLY (without BEGIN/END headers)",
            ),
        ),
        migrations.AddField(
            model_name="gatewaysettings",
            name="jayapay_ph_public_key",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional: Platform PUBLIC KEY untuk verifikasi callback",
            ),
        ),
        migrations.AddField(
            model_name="gatewaysettings",
            name="jayapay_ph_redirect_url",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("JAYAPAY", "Jayapay"),
                    ("JAYAPAY_PH", "Jayapay Philippines"),
                    ("KLIKPAY", "Klikpay"),
                    ("USD_GATEWAY", "USD Gateway"),
                ],
                max_length=20,
            ),
        ),
    ]

