# Generated by Django 4.2.13 on 2026-08-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0014_atpay_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaysettings',
            name='bankpay_api_url',
            field=models.CharField(blank=True, default='https://pay.bankpay.cfd', max_length=255),
        ),
        migrations.AddField(
            model_name='gatewaysettings',
            name='bankpay_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatewaysettings',
            name='bankpay_key',
            field=models.CharField(blank=True, default='', help_text='MERCHANT_KEY untuk signature MD5', max_length=255),
        ),
        migrations.AddField(
            model_name='gatewaysettings',
            name='bankpay_member_id',
            field=models.CharField(blank=True, default='', help_text='Merchant ID dari BankPay', max_length=100),
        ),
        migrations.AddField(
            model_name='gatewaysettings',
            name='bankpay_return_url',
            field=models.CharField(blank=True, default='', help_text='URL redirect setelah pembayaran selesai', max_length=512),
        ),
    ]
