# Generated by Django 4.2.13 on 2026-08-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0015_bankpay_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='gateway',
            field=models.CharField(choices=[('JAYAPAY', 'Jayapay'), ('JAYAPAY_PH', 'Jayapay Philippines'), ('KLIKPAY', 'Klikpay'), ('USD_GATEWAY', 'USD Gateway'), ('PPAYPROS', 'PPay Pros'), ('CLIENTHUB', 'ClientHub'), ('SITRANSFERHUB', 'SiTransfer Hub'), ('ATPAY', 'ATPAY'), ('BANKPAY', 'BankPay')], max_length=20),
        ),
    ]
