# Generated by Django 4.2.13 on 2026-08-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0016_bankpay_gateway_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='payment_url',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
