# Generated by Django 4.2.13 on 2026-09-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0020_gatewaysettings_batpay_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaysettings',
            name='nextpay_api_key',
            field=models.CharField(blank=True, default='', help_text='X-API-Key merchant (ak_...)', max_length=255),
        ),
        migrations.AddField(
            model_name='gatewaysettings',
            name='nextpay_api_url',
            field=models.CharField(blank=True, default='https://api.nextcdn.online', help_text='Base URL NextPay', max_length=255),
        ),
        migrations.AddField(
            model_name='gatewaysettings',
            name='nextpay_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatewaysettings',
            name='nextpay_return_url',
            field=models.CharField(blank=True, default='', help_text='URL redirect setelah pembayaran selesai (opsional)', max_length=512),
        ),
        migrations.AddField(
            model_name='gatewaysettings',
            name='nextpay_secret_key',
            field=models.TextField(blank=True, default='', help_text='Secret key HMAC-SHA256 (347 karakter - jangan VARCHAR(255))'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='gateway',
            field=models.CharField(choices=[('JAYAPAY', 'Jayapay'), ('JAYAPAY_PH', 'Jayapay Philippines'), ('KLIKPAY', 'Klikpay'), ('USD_GATEWAY', 'USD Gateway'), ('PPAYPROS', 'PPay Pros'), ('CLIENTHUB', 'ClientHub'), ('SITRANSFERHUB', 'SiTransfer Hub'), ('ATPAY', 'ATPAY'), ('BANKPAY', 'BankPay'), ('QRIS', 'QRIS Manual'), ('REEPAY', 'Reepay'), ('BATPAY', 'BatPay'), ('NEXTPAY', 'NextPay')], max_length=20),
        ),
    ]
