# Generated by Django 4.2.7 on 2025-10-05 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('min_withdrawal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_withdrawal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('withdrawal_fee', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('processing_time', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_banks', to='banks.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_banks',
                'unique_together': {('user', 'account_number')},
            },
        ),
    ]
