# Generated by Django 4.2.7 on 2025-10-23 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("banks", "0002_alter_userbank_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_banks_per_user",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Maksimal jumlah bank yang bisa dimiliki user",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bank Settings",
                "verbose_name_plural": "Bank Settings",
                "db_table": "bank_settings",
            },
        ),
        migrations.RemoveConstraint(
            model_name="userbank",
            name="unique_user_bank",
        ),
        migrations.AlterField(
            model_name="userbank",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="userbank",
            constraint=models.UniqueConstraint(
                fields=("user", "bank"), name="unique_user_bank_combination"
            ),
        ),
        migrations.AddConstraint(
            model_name="userbank",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user",),
                name="unique_default_bank_per_user",
            ),
        ),
    ]
