# Generated by Django 4.2.13 on 2026-05-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_bank_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='banksettings',
            name='max_banks_foreign_per_user',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maksimal jumlah bank non-IDR yang bisa dimiliki user (0 = ikut Max Banks Per User)'),
        ),
        migrations.AddField(
            model_name='banksettings',
            name='max_banks_idr_per_user',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maksimal jumlah bank IDR yang bisa dimiliki user (0 = ikut Max Banks Per User)'),
        ),
    ]
