# Generated by Django 4.2.13 on 2026-05-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banks", "0006_banksettings_max_banks_foreign_per_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbank",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]

