# Generated by Django 4.2.13 on 2026-05-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_userbank_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='currency_code',
            field=models.CharField(choices=[('IDR', 'IDR (Rupiah)'), ('USD', 'USD (US Dollar)'), ('EUR', 'EUR (Euro)'), ('SGD', 'SGD (Singapore Dollar)'), ('MYR', 'MYR (Ringgit)'), ('PHP', 'PHP (Philippine Peso)')], default='IDR', help_text='Kategori currency untuk bank ini (mis. bank IDR vs bank USD).', max_length=10),
        ),
    ]
