# Generated by Django 4.2.7 on 2025-10-05 09:15

from django.db import migrations, models


def cleanup_rank(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.exclude(rank__isnull=True):
        val = user.rank
        try:
            s = str(val).strip()
        except Exception:
            s = ''
        if s not in {'1', '2', '3', '4', '5', '6'}:
            user.rank = None
            user.save(update_fields=['rank'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cleanup_rank, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], null=True),
        ),
    ]
