# Generated by Django 4.2.7 on 2025-11-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_rank"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referral_code_length",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Panjang kode referral (minimum 4, maksimum 20)",
                    ),
                ),
                (
                    "referral_code_case",
                    models.CharField(
                        choices=[
                            ("upper", "Huruf Besar Semua (ABCD123)"),
                            ("lower", "Huruf Kecil Semua (abcd123)"),
                            ("mixed", "Campuran Huruf & Angka (AbCd123)"),
                            ("numbers_only", "Angka Saja (123456)"),
                            ("letters_only", "Huruf Saja (ABCDEF)"),
                        ],
                        default="upper",
                        help_text="Format karakter untuk kode referral",
                        max_length=20,
                    ),
                ),
                (
                    "exclude_similar_chars",
                    models.BooleanField(
                        default=True,
                        help_text="Hindari karakter yang mirip (0, O, 1, I, l)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "General Setting",
                "verbose_name_plural": "General Settings",
            },
        ),
    ]
