# Generated by Django 4.2.7 on 2025-11-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_generalsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsetting",
            name="referral_code_pattern",
            field=models.CharField(
                blank=True,
                help_text="Pola karakter, mis. 'L D D L' atau 'A A D D'. Token: U=huruf besar, l=huruf kecil, L=huruf (besar/kecil), D=angka, A=alphanumeric.",
                max_length=100,
                null=True,
            ),
        ),
    ]
