# Generated by Django 4.2.7 on 2025-11-04 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_generalsetting_referral_code_pattern"),
    ]

    operations = [
        migrations.CreateModel(
            name="RankLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                        ],
                        unique=True,
                    ),
                ),
                ("title", models.CharField(default="Rank", max_length=100)),
                (
                    "missions_required_total",
                    models.PositiveIntegerField(
                        help_text="Total misi selesai (distinct) untuk mencapai rank ini"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rank Level",
                "verbose_name_plural": "Rank Levels",
                "db_table": "rank_levels",
                "ordering": ["rank"],
            },
        ),
    ]
