# Generated by Django 4.2.13 on 2025-11-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_ranklevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="withdraw_pin",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
