# Generated by Django 4.2.13 on 2025-11-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_user_withdraw_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsetting",
            name="auto_login_on_register",
            field=models.BooleanField(
                default=True,
                help_text="Jika ON, user baru langsung mendapatkan token login setelah register",
            ),
        ),
    ]
