# Generated by Django 4.2.7 on 2025-11-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_generalsetting_auto_login_on_register"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsetting",
            name="rank_basis",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("missions", "Berdasarkan misi selesai"),
                    ("downlines_total", "Jumlah anggota downline"),
                    ("downlines_active", "Jumlah downline aktif"),
                ],
                default="missions",
                help_text="Basis perhitungan rank: misi selesai, jumlah downline, atau downline aktif",
            ),
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="rank_count_levels_upto",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Hitung downline hingga level ini (1=Level 1 saja, 2=Level 1+2, dst.)",
            ),
        ),
    ]