# Generated by Django 4.2.7 on 2025-11-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_generalsetting_rank_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsetting",
            name="rank_use_missions",
            field=models.BooleanField(
                default=True,
                help_text="Jika ON, progres misi selesai (distinct) digunakan untuk rank",
            ),
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="rank_use_downlines_total",
            field=models.BooleanField(
                default=False,
                help_text="Jika ON, jumlah anggota downline (hingga level yang dipilih) digunakan untuk rank",
            ),
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="rank_use_downlines_active",
            field=models.BooleanField(
                default=False,
                help_text="Jika ON, jumlah downline aktif (punya investasi status ACTIVE) digunakan untuk rank",
            ),
        ),
    ]