# Generated by Django 5.0.6 on 2025-12-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_generalsetting_rank_basis_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsetting",
            name="registration_bonus_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="registration_bonus_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="registration_bonus_wallet",
            field=models.CharField(
                choices=[
                    ("balance", "Balance"),
                    ("balance_deposit", "Balance Deposit"),
                ],
                default="balance",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ranklevel",
            name="missions_required_total",
            field=models.PositiveIntegerField(
                help_text="Ambang jumlah progres untuk rank ini. Jika basis=missions, ini adalah total misi selesai (distinct). Jika basis=downlines_total, isi dengan jumlah anggota downline. Jika basis=downlines_active, isi dengan jumlah downline aktif."
            ),
        ),
    ]
