# Generated by Django 5.0.6 on 2026-01-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_useraddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ranklevel",
            name="rank",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                ],
                unique=True,
            ),
        ),
    ]
