# Generated by Django 5.0.6 on 2026-01-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_ranklevel_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
