# Generated by Django 5.0.6 on 2026-01-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_user_last_login_ip"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("otp_code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("verified", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Phone OTP",
                "verbose_name_plural": "Phone OTPs",
            },
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="otp_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable WhatsApp OTP verification for registration",
            ),
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="verifyway_api_key",
            field=models.CharField(
                blank=True,
                help_text="API Key for VerifyWay WhatsApp OTP",
                max_length=255,
            ),
        ),
    ]
