# Generated by Django 5.0.6 on 2026-01-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_generalsetting_whatsapp_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneotp",
            name="verification_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="phoneotp",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
