# Generated by Django 5.0.6 on 2026-01-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_phoneotp_verification_id_alter_phoneotp_otp_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsetting",
            name="verifynow_api_key",
            field=models.CharField(
                blank=True,
                help_text="Base64 Encrypted Password for VerifyNow (Message Central)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="verifynow_customer_id",
            field=models.CharField(
                blank=True,
                help_text="Customer ID for VerifyNow (Message Central)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="generalsetting",
            name="verifyway_api_key",
            field=models.CharField(
                blank=True,
                help_text="API Key for VerifyWay WhatsApp OTP (Deprecated)",
                max_length=255,
            ),
        ),
    ]
