# Generated by Django 5.0.6 on 2026-02-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_generalsetting_verifynow_api_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminDecodeTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decode API Response",
                "verbose_name_plural": "Decode API Response",
                "managed": False,
            },
        ),
    ]
