# Generated by Django 5.0.6 on 2026-02-15 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_generalsetting_require_withdraw_pin_on_register"),
        ("accounts", "0018_admindecodetool"),
    ]

    operations = []
