# Generated by Django 5.0.6 on 2026-03-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_user_balance_hold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalsetting",
            name="rank_basis",
            field=models.CharField(
                choices=[
                    ("missions", "Berdasarkan misi selesai"),
                    ("downlines_total", "Jumlah anggota downline"),
                    ("downlines_active", "Jumlah downline aktif"),
                    ("deposit_self_total", "Jumlah deposit sendiri"),
                ],
                default="missions",
                help_text="Basis perhitungan rank: misi selesai, jumlah downline, atau downline aktif",
                max_length=20,
            ),
        ),
    ]
