# Generated by Django 5.0.6 on 2026-03-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_alter_generalsetting_rank_basis"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsetting",
            name="frontend_url",
            field=models.URLField(
                blank=True,
                help_text="URL domain frontend (contoh: https://my-frontend.com)",
                max_length=255,
                null=True,
            ),
        ),
    ]
