# Generated by Django 5.0.6 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0026_ranklevel_multi_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsetting",
            name="referral_daily_invite_limit",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Batas undang per hari via referral code (0 = tanpa batas)",
            ),
        ),
    ]

