# Generated by Django 4.2.13 on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0027_generalsetting_referral_daily_invite_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsetting",
            name="currency_code",
            field=models.CharField(
                choices=[
                    ("IDR", "IDR (Rupiah)"),
                    ("USD", "USD (US Dollar)"),
                    ("EUR", "EUR (Euro)"),
                    ("SGD", "SGD (Singapore Dollar)"),
                    ("MYR", "MYR (Ringgit)"),
                ],
                default="IDR",
                help_text="Pilih currency untuk format tampilan nominal (simbol, pemisah ribuan, pemisah desimal).",
                max_length=10,
            ),
        ),
    ]

