# Generated by Django 4.2.13 on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0028_generalsetting_currency_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsetting",
            name="fazpass_gateway_key",
            field=models.CharField(
                blank=True,
                help_text="Gateway key untuk Fazpass OTP",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="fazpass_merchant_key",
            field=models.CharField(
                blank=True,
                help_text="Merchant key untuk Fazpass (Bearer token)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VERIFYNOW", "VerifyNow"),
                    ("VERIFYWAY", "VerifyWay (Legacy)"),
                    ("FAZPASS", "Fazpass"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]

