# Generated by Django 4.2.13 on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0029_generalsetting_fazpass_and_phoneotp_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsetting",
            name="otp_provider",
            field=models.CharField(
                choices=[
                    ("AUTO", "Auto (prioritas: VerifyNow \u2192 Fazpass \u2192 VerifyWay)"),
                    ("VERIFYNOW", "VerifyNow (Message Central)"),
                    ("FAZPASS", "Fazpass"),
                    ("VERIFYWAY", "VerifyWay (Legacy)"),
                ],
                default="AUTO",
                help_text="Pilih provider OTP yang dipakai. Jika AUTO, sistem akan memilih berdasarkan credential yang tersedia.",
                max_length=20,
            ),
        ),
    ]

