# Generated by Django 4.2.13 on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0030_generalsetting_otp_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsetting",
            name="currency_rate_to_idr",
            field=models.DecimalField(
                decimal_places=6,
                default=1,
                help_text="Kurs untuk konversi ke Rupiah. Contoh: jika currency=USD dan 1 USD = 16000 IDR, isi 16000.",
                max_digits=20,
            ),
        ),
    ]

