# Generated by Django 4.2.13 on 2026-05-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_generalsetting_currency_rate_to_idr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='currency_code',
            field=models.CharField(choices=[('IDR', 'IDR (Rupiah)'), ('USD', 'USD (US Dollar)'), ('EUR', 'EUR (Euro)'), ('SGD', 'SGD (Singapore Dollar)'), ('MYR', 'MYR (Ringgit)'), ('PHP', 'PHP (Philippine Peso)')], default='IDR', help_text='Pilih currency untuk format tampilan nominal (simbol, pemisah ribuan, pemisah desimal).', max_length=10),
        ),
    ]
