# Generated by Django 4.2.13 on 2026-05-24 00:21

from django.db import migrations, models


def seed_currency_rates(apps, schema_editor):
    GeneralSetting = apps.get_model("accounts", "GeneralSetting")
    CurrencyRate = apps.get_model("accounts", "CurrencyRate")

    try:
        CurrencyRate.objects.get_or_create(code="IDR", defaults={"rate_to_idr": 1, "is_active": True})
    except Exception:
        pass

    try:
        gs = GeneralSetting.objects.order_by("-updated_at").first()
    except Exception:
        gs = None

    if not gs:
        return

    code = (getattr(gs, "currency_code", None) or "IDR").strip().upper()
    if code and code != "IDR":
        rate = getattr(gs, "currency_rate_to_idr", None) or 1
        try:
            CurrencyRate.objects.update_or_create(code=code, defaults={"rate_to_idr": rate, "is_active": True})
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_generalsetting_currency_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('IDR', 'IDR (Rupiah)'), ('USD', 'USD (US Dollar)'), ('EUR', 'EUR (Euro)'), ('SGD', 'SGD (Singapore Dollar)'), ('MYR', 'MYR (Ringgit)'), ('PHP', 'PHP (Philippine Peso)')], max_length=10, unique=True)),
                ('rate_to_idr', models.DecimalField(decimal_places=6, default=1, help_text='Kurs ke IDR. Contoh: 1 USD = 16000 IDR, isi 16000.', max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'currency_rates',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='allowed_currency_codes',
            field=models.CharField(blank=True, default='', help_text='Daftar currency yang diizinkan (pisahkan dengan koma), contoh: USD,PHP. Kosong = hanya currency_code.', max_length=100),
        ),
        migrations.RunPython(seed_currency_rates, reverse_code=migrations.RunPython.noop),
    ]
