# Generated by Django 4.2.13 on 2026-05-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_currencyrate_generalsetting_allowed_currency_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='secondary_currency_code',
            field=models.CharField(blank=True, choices=[('IDR', 'IDR (Rupiah)'), ('USD', 'USD (US Dollar)'), ('EUR', 'EUR (Euro)'), ('SGD', 'SGD (Singapore Dollar)'), ('MYR', 'MYR (Ringgit)'), ('PHP', 'PHP (Philippine Peso)')], default='', help_text='Currency kedua (opsional). Jika diisi, sistem menampilkan 2 currency (main + secondary) dan bisa konversi secondary ↔ main via rate.', max_length=10),
        ),
    ]
