# Generated by Django 4.2.13 on 2026-05-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_generalsetting_secondary_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='secondary_rate_per_main',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Kurs SECONDARY per 1 MAIN. Contoh: MAIN=USD, SECONDARY=PHP, jika 1 USD = 62 PHP, isi 62.', max_digits=20),
        ),
    ]
