# Generated by Django 4.2.13 on 2026-05-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_generalsetting_secondary_rate_per_main'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyRate',
        ),
        migrations.RemoveField(
            model_name='generalsetting',
            name='allowed_currency_codes',
        ),
        migrations.RemoveField(
            model_name='generalsetting',
            name='currency_rate_to_idr',
        ),
    ]
