# Generated by Django 4.2.13 on 2026-07-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_generalsetting_active_member_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranklevel',
            name='description',
            field=models.TextField(blank=True, help_text='Deskripsi untuk rank ini.', null=True),
        ),
    ]
