# Generated by Django 4.2.13 on 2026-07-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_ranklevel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='bypass_otp_on_register',
            field=models.BooleanField(default=False, help_text='Jika ON, OTP verification di-skip saat registrasi (nomor Indonesia bisa daftar tanpa OTP)'),
        ),
    ]
