# Generated by Django 4.2.13 on 2026-08-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='require_referral_code_on_register',
            field=models.BooleanField(default=False, help_text='Jika ON, referral code wajib diisi saat registrasi'),
        ),
    ]
