# Generated by Django 4.2.13 on 2025-11-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportchatthread_supportchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportlink',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='support/icons/'),
        ),
    ]
