"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env if present without overriding existing environment
load_dotenv(BASE_DIR / '.env', override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-&_)yq3essw31tdnp_dpq+t-r2xwbl#m2bvo*nocw7871_xg$x@')

DEBUG = os.environ.get('DEBUG', 'True').strip().lower() in ('true', '1', 'yes', 'on')

# Security: Restrict allowed hosts
ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get(
        'ALLOWED_HOSTS',
        'localhost,127.0.0.1,croucloud.xyz,www.croucloud.xyz'
    ).split(',') if host.strip()
]

# Add domain from APP_DOMAIN to allowed hosts
APP_DOMAIN = os.environ.get('APP_DOMAIN', 'croucloud.xyz').strip()
if APP_DOMAIN and APP_DOMAIN not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(APP_DOMAIN.split(':')[0])  # Add domain without port

# Add ngrok domains from environment variables
NGROK_DOMAINS = os.environ.get('NGROK_DOMAINS', '').strip()
if NGROK_DOMAINS:
    ngrok_domains_list = [domain.strip() for domain in NGROK_DOMAINS.split(',') if domain.strip()]
    ALLOWED_HOSTS.extend(ngrok_domains_list)

# Admin URL base path (do not use default '/admin')
ADMIN_URL = os.environ.get('ADMIN_URL', 'backend-admin').strip()

# ---------------------------------------------------------------------------
# Security hardening — cookie flags
# ---------------------------------------------------------------------------
# Session cookie (dipakai admin panel): HttpOnly + SameSite=Lax selalu.
# Secure hanya aktif di production (DEBUG=False) supaya tetap jalan di http://localhost saat dev.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG

# CSRF cookie: Secure mengikuti production, SameSite=Lax.
# HttpOnly=True mencegah JS membaca token (paling aman terhadap XSS).
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG
# ---------------------------------------------------------------------------


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    'accounts',
    'products',
    'attendance',
    'vouchers',
    'missions',
    'banks',
    'withdrawal',
    'deposits',
    'support',
    'news',
    'roulette',
    'reviews',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'config.encoded_path_middleware.EncodedApiPathMiddleware',
    'config.security_middleware.DomainIPSecurityMiddleware',  # Add security middleware
    # 'config.mobile_restriction_middleware.MobileOnlyMiddleware',  # Mobile restriction middleware
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'config.unauthorized_middleware.UnauthorizedBlankPageMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'products/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


VALID_PG_SSLMODES = {'disable', 'allow', 'prefer', 'require', 'verify-ca', 'verify-full'}
DATABASE_SSLMODE = os.environ.get('DATABASE_SSLMODE', 'require').strip().lower()
if DATABASE_SSLMODE in {'enable', 'enabled', 'on', 'true', '1'}:
    DATABASE_SSLMODE = 'require'
if DATABASE_SSLMODE not in VALID_PG_SSLMODES:
    DATABASE_SSLMODE = 'require'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DATABASE_NAME', 'postgres'),
        'USER': os.environ.get('DATABASE_USER', 'postgres'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', '').strip(),
        'HOST': os.environ.get('DATABASE_HOST', 'localhost'),
        'PORT': os.environ.get('DATABASE_PORT', '5432'),
        # Disable server-side cursors to be compatible with poolers (e.g., Neon/PgBouncer transaction pooling)
        'DISABLE_SERVER_SIDE_CURSORS': True,
        # Set CONN_MAX_AGE to 0 for PgBouncer in transaction mode to prevent errors
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '0')),
        'OPTIONS': {
            'sslmode': DATABASE_SSLMODE,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'id'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = False

CURRENCY_CODE = os.environ.get('CURRENCY_CODE', 'IDR').strip()
CURRENCY_SYMBOL = os.environ.get('CURRENCY_SYMBOL', 'Rp').strip()
CURRENCY_DECIMALS = int(os.environ.get('CURRENCY_DECIMALS', '2'))
CURRENCY_THOUSAND_SEPARATOR = os.environ.get('CURRENCY_THOUSAND_SEPARATOR', '.')
CURRENCY_DECIMAL_SEPARATOR = os.environ.get('CURRENCY_DECIMAL_SEPARATOR', ',')
CURRENCY_SYMBOL_POSITION = os.environ.get('CURRENCY_SYMBOL_POSITION', 'prefix').strip().lower()
CURRENCY_SYMBOL_SPACE = os.environ.get('CURRENCY_SYMBOL_SPACE', 'True').strip().lower() in ('true', '1', 'yes', 'on')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Use the standard '/static/' URL so Django admin looks under /static/admin/
STATIC_URL = '/static/'
STATIC_ROOT = os.environ.get('STATIC_ROOT', os.path.join(BASE_DIR, 'staticfiles'))
STATICFILES_DIRS = []

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

# Ensure uploaded files/directories have secure, readable permissions for web server
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.auth.BannedAwareJWTAuthentication',
        'accounts.auth.BannedAwareSessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'accounts.renderers.SaltedBase64ReverseJSONRenderer',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'config.throttling.drf_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
    # Rate limiting (throttling)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
        'config.throttling.RoleBasedUserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Global per-IP for anonymous and per-user for authenticated
        'anon': '2000/min',
        'user': '5000/min',
        'admin_user': '10000/min',
        # Scoped endpoints
        'auth_login': '5000/min',
        'auth_register': '20/min',
        'auth_request_otp': '1/min',
        'auth_password_change': '2/min',
        'auth_pin': '5/min',
        'deposit_initiate': '6/min',
        'gateway_callback': '120/min',
        'missions_claim': '15/min',
        'voucher_claim': '30/min',
        # Additional scoped endpoints
        'attendance_claim': '15/min',
        'withdrawals': '15/min',
        'withdraw_admin_initiate': '30/min',
        'products_purchase': '15/min',
        'investments_claim_profit': '15/min',
        'transactions': '20/min',
        'banks_user': '20/min',
        'banks_list': '20/min',
        'reviews_create': '10/min',
        'reviews_like': '60/min',
        'admin_analytics': '60/min',
        'analytics_investors_monthly': '120/min',
    },
}

# DRF Spectacular settings for API documentation
SPECTACULAR_SETTINGS = {
    'TITLE': 'Investment Platform API Documentation',
    'DESCRIPTION': '''
    API Documentation for Investment Platform.
    
    Authentication:
    - All endpoints require authentication token except registration
    - Add token to header: `Authorization: Bearer <access_token>`
    
    User API:
    - View products and make investments
    - Manage transactions and referrals
    - View balance and history
    
    Admin API:
    - Manage products and settings
    - Monitor all transactions
    - User management
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'TAGS': [
        {'name': 'User API', 'description': 'Endpoints accessible to regular users'},
        {'name': 'Admin API', 'description': 'Endpoints accessible only to admin users'},
    ],
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'defaultModelsExpandDepth': -1,
    }
}

RESPONSE_ENCODE_ENABLED = True
RESPONSE_ENCODE_SALT = os.environ.get('RESPONSE_ENCODE_SALT', 'KXXADFDFDF')
PATH_ENCODE_ENABLED = True

# Jayapay integration (optional)
JAYAPAY_ENABLED = os.environ.get('JAYAPAY_ENABLED', 'False').strip().lower() in ('true', '1', 'yes', 'on')
JAYAPAY_MERCHANT_CODE = os.environ.get('JAYAPAY_MERCHANT_CODE', '').strip()
# PEM body without headers; strip quotes/spaces if provided in .env
JAYAPAY_PRIVATE_KEY = os.environ.get('JAYAPAY_PRIVATE_KEY', '').strip().strip('"').strip("'")
APP_DOMAIN = os.environ.get('APP_DOMAIN', 'api.ggeeccss.xyz').strip()
JAYAPAY_NOTIFY_URL = f"https://{APP_DOMAIN}/api/withdrawals/jayapay/callback/"

# USD payout gateway (payment on behalf / payout)
USD_PAYOUT_ENABLED = os.environ.get('USD_PAYOUT_ENABLED', 'False').strip().lower() in ('true', '1', 'yes', 'on')
USD_PAYOUT_API_URL = os.environ.get('USD_PAYOUT_API_URL', 'https://taslk.gctpk.com/payout/singleOrder').strip().strip('"').strip("'")
USD_PAYOUT_MER_NO = os.environ.get('USD_PAYOUT_MER_NO', '').strip()
USD_PAYOUT_SIGN_KEY = os.environ.get('USD_PAYOUT_SIGN_KEY', '').strip()
USD_PAYOUT_RSA_PRIVATE_KEY = os.environ.get('USD_PAYOUT_RSA_PRIVATE_KEY', '').strip().strip('"').strip("'")
USD_PAYOUT_BUSI_CODE = os.environ.get('USD_PAYOUT_BUSI_CODE', '224001').strip()
USD_PAYOUT_NOTIFY_URL = f"https://{APP_DOMAIN}/api/withdrawals/usd-payout/callback/"

# Deposit kini menggunakan konfigurasi dari admin (GatewaySettings)

# CORS settings - Restrict to allowed origins only
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'False').lower() == 'true'
CORS_ALLOW_CREDENTIALS = True

# Define allowed origins for CORS
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in os.environ.get('CORS_ALLOWED_ORIGINS', 
        'https://ggeecsxio.com,https://api.ggeeccss.xyz,http://localhost:5174,http://127.0.0.1:5174'
    ).split(',') if origin.strip()
]

# Add ngrok domains from environment variables to CORS allowed origins
NGROK_HTTPS_DOMAINS = os.environ.get('NGROK_HTTPS_DOMAINS', '').strip()
if NGROK_HTTPS_DOMAINS:
    ngrok_https_list = [domain.strip() for domain in NGROK_HTTPS_DOMAINS.split(',') if domain.strip()]
    CORS_ALLOWED_ORIGINS.extend(ngrok_https_list)

# Add APP_DOMAIN to CORS allowed origins
APP_DOMAIN = os.environ.get('APP_DOMAIN', 'api.ggeeccss.xyz').strip()
if APP_DOMAIN:
    app_origins = [
        f"http://{APP_DOMAIN}",
        f"https://{APP_DOMAIN}",
    ]
    for origin in app_origins:
        if origin not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(origin)

# Capacitor/mobile WebView support via regex (e.g., capacitor://localhost)
CORS_ALLOWED_ORIGIN_REGEXES = [
    origin.strip() for origin in os.environ.get('CORS_ALLOWED_ORIGIN_REGEXES', '^capacitor://localhost$,^https?://localhost(:\d+)?$,^ionic://localhost$').split(',') if origin.strip()
]
# Optional: allow null origin (e.g., file:// schemes in some WebViews)
CORS_ALLOW_NULL_ORIGIN = os.environ.get('CORS_ALLOW_NULL_ORIGIN', 'False').lower() == 'true'

# CSRF: trust frontend dev origins
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.environ.get('CSRF_TRUSTED_ORIGINS',
        'https://ggeecsxio.com,https://api.ggeeccss.xyz,http://localhost:5174,http://127.0.0.1:5174,https://localhost,http://localhost,capacitor://localhost'
    ).split(',') if origin.strip()
]

# Add ngrok domains from environment variables to CSRF trusted origins
NGROK_HTTPS_DOMAINS = os.environ.get('NGROK_HTTPS_DOMAINS', '').strip()
if NGROK_HTTPS_DOMAINS:
    ngrok_https_list = [domain.strip() for domain in NGROK_HTTPS_DOMAINS.split(',') if domain.strip()]
    CSRF_TRUSTED_ORIGINS.extend(ngrok_https_list)

# Add APP_DOMAIN to CSRF trusted origins
if APP_DOMAIN:
    csrf_origins = [
        f"http://{APP_DOMAIN}",
        f"https://{APP_DOMAIN}",
    ]
    for origin in csrf_origins:
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)

# Security Settings for Domain/IP Restriction
# Force bypass to fix "Access denied" in development
BYPASS_DOMAIN_IP_SECURITY = os.environ.get('BYPASS_DOMAIN_IP_SECURITY', 'False').strip().lower() in ('true', '1', 'yes', 'on')

# JWT configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.environ.get('JWT_ACCESS_MINUTES', '15'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.environ.get('JWT_REFRESH_DAYS', '7'))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': os.environ.get('JWT_ALGORITHM', 'HS256'),
    'SIGNING_KEY': os.environ.get('JWT_SIGNING_KEY', os.environ.get('SECRET_KEY', '')),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Allowed domains (can be set via environment variable)
ALLOWED_DOMAINS = [
    domain.strip() for domain in os.environ.get('ALLOWED_DOMAINS', 
        'localhost,127.0.0.1,api.ggeeccss.xyz,ggeecsxio.com'
    ).split(',') if domain.strip()
]

# Allowed IP addresses (can be set via environment variable)  
ALLOWED_IPS = [
    ip.strip() for ip in os.environ.get('ALLOWED_IPS',
        '127.0.0.1,::1'
    ).split(',') if ip.strip()
]

# Allowed IP ranges (can be set via environment variable)
ALLOWED_IP_RANGES = [
    range_ip.strip() for range_ip in os.environ.get('ALLOWED_IP_RANGES',
        '192.168.0.0/16,10.0.0.0/8,172.16.0.0/12'
    ).split(',') if range_ip.strip()
]

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'accounts.auth.PhoneOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',  # Keep default backend as fallback
]

# Logging configuration for detailed error tracking
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'withdrawal': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'products': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}

from django.db.backends.signals import connection_created
from django.dispatch import receiver

@receiver(connection_created)
def _ensure_public_schema(sender, connection, **kwargs):
    try:
        with connection.cursor() as cursor:
            cursor.execute("SET search_path TO public;")
    except Exception:
        pass
