# Generated by Django 4.2.7 on 2025-10-05 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_repeatable', models.BooleanField(default=False)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('purchase', 'Purchase-based'), ('service', 'Service claim-based'), ('referral', 'Referral-based')], max_length=20)),
                ('requirement', models.PositiveIntegerField(help_text='Threshold count to complete/claim mission')),
                ('reward', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reward_balance_type', models.CharField(choices=[('balance', 'Balance'), ('balance_deposit', 'Balance Deposit')], default='balance', max_length=20)),
                ('referral_levels', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'missions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionUserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_count', models.PositiveIntegerField(default=0)),
                ('last_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mission_user_states',
                'unique_together': {('user', 'mission')},
            },
        ),
    ]
