# Generated by Django 4.2.7 on 2025-10-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="title",
            field=models.CharField(
                default="Mission Title",
                help_text="Judul singkat untuk mission",
                max_length=100,
            ),
        ),
    ]
