# Generated by Django 5.0.6 on 2026-02-12 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0002_mission_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Dibuat"
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="description",
            field=models.CharField(
                help_text="Deskripsi singkat misi",
                max_length=255,
                verbose_name="Deskripsi",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Jika tidak aktif, misi disembunyikan dan progres tidak dihitung",
                verbose_name="Aktif",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="is_repeatable",
            field=models.BooleanField(
                default=False,
                help_text="Jika aktif, misi dapat diklaim berkali-kali setiap kelipatan requirement tercapai",
                verbose_name="Dapat diklaim berulang",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Label tingkat/kesulitan; tidak memengaruhi perhitungan",
                null=True,
                verbose_name="Level (opsional)",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="referral_levels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Daftar level downline (mis. [1], [1,2], [1,2,3]) yang disertakan dalam perhitungan",
                verbose_name="Level downline yang dihitung",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="requirement",
            field=models.PositiveIntegerField(
                help_text="Ambang progres untuk 1 kali klaim (contoh: 20 berarti setiap 20 progres dapat klaim 1x)",
                verbose_name="Requirement",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="reward",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Nominal hadiah per klaim",
                max_digits=15,
                verbose_name="Hadiah per klaim",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="reward_balance_type",
            field=models.CharField(
                choices=[
                    ("balance", "Saldo Utama"),
                    ("balance_deposit", "Saldo Deposit"),
                ],
                default="balance",
                help_text="Pilih dompet penyaluran hadiah: Saldo Utama atau Saldo Deposit",
                max_length=20,
                verbose_name="Dompet hadiah",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="title",
            field=models.CharField(
                default="Judul Misi",
                help_text="Judul singkat misi (tampil di admin dan aplikasi)",
                max_length=100,
                verbose_name="Judul",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="type",
            field=models.CharField(
                choices=[
                    ("purchase", "Berdasarkan pembelian/aktivasi"),
                    (
                        "purchase_self",
                        "Berdasarkan pembelian/aktivasi oleh user sendiri",
                    ),
                    ("service", "Berdasarkan klaim layanan/profit"),
                    (
                        "service_self",
                        "Berdasarkan klaim layanan/profit oleh user sendiri",
                    ),
                    ("deposit", "Berdasarkan deposit oleh downline"),
                    ("deposit_self", "Berdasarkan total deposit oleh user sendiri"),
                    ("referral", "Berdasarkan referral/downline"),
                    ("active_downline", "Berdasarkan total downline aktif"),
                    ("withdrawal", "Berdasarkan penarikan (withdraw) selesai"),
                ],
                help_text="Pilih jenis misi: referral/purchase/purchase_self/service/service_self/deposit_self/withdrawal sesuai logika perhitungan",
                max_length=20,
                verbose_name="Jenis Misi",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Diubah"),
        ),
    ]
