# Generated by Django 4.2.13 on 2026-07-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_alter_mission_created_at_alter_mission_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='is_time_limited',
            field=models.BooleanField(default=False, help_text='Jika aktif, progres misi hanya dihitung untuk periode waktu tertentu', verbose_name='Dibatasi Waktu'),
        ),
        migrations.AddField(
            model_name='mission',
            name='time_period_days',
            field=models.PositiveIntegerField(blank=True, help_text='Jumlah hari untuk periode waktu (mis. 7 untuk mingguan, 30 untuk bulanan)', null=True, verbose_name='Periode (Hari)'),
        ),
    ]
