# Generated by Django 4.2.13 on 2026-07-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_mission_is_time_limited_mission_time_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionuserstate',
            name='period_start',
            field=models.DateTimeField(blank=True, help_text='Waktu mulai periode untuk misi yang dibatasi waktu', null=True),
        ),
    ]
