# Generated by Django 4.2.7 on 2025-10-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='voucher',
            name='rank_rewards',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('random', 'Random Range'), ('rank', 'Rank Based')], default='fixed', max_length=20),
        ),
    ]
