# Generated by Django 5.0.6 on 2026-02-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0002_voucher_min_amount_voucher_rank_rewards_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="start_at",
            field=models.DateTimeField(
                blank=True, help_text="Waktu mulai klaim voucher", null=True
            ),
        ),
    ]
