# Generated by Django 5.0.6 on 2026-02-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0003_voucher_start_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="claim_mode",
            field=models.CharField(
                choices=[
                    ("manual", "Manual (Input Code)"),
                    ("automatic", "Automatic (Click to Claim)"),
                ],
                default="manual",
                help_text="Manual: User harus input kode (tidak muncul di list). Automatic: User tinggal klik (muncul di list).",
                max_length=20,
            ),
        ),
    ]
