# Generated by Django 5.0.6 on 2026-02-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0004_voucher_claim_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="is_daily_claim",
            field=models.BooleanField(
                default=False,
                help_text="Jika aktif, user bisa klaim lagi besoknya (reset harian)",
            ),
        ),
    ]
