# Generated by Django 4.2.13 on 2026-07-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0005_roulette_ticket_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='rouletteprize',
            name='image',
            field=models.ImageField(blank=True, help_text='Gambar hadiah roulette', null=True, upload_to='roulette/'),
        ),
    ]
