JAYAPAY_BANKS = [
    {"bankCode": "116", "bankAbbreviation": "ACEH", "theNameOfTheBank": "Bank Aceh Syariah"},
    {"bankCode": "1160", "bankAbbreviation": "ACEH_UUS", "theNameOfTheBank": "Bank Agris UUS"},
    {"bankCode": "945", "bankAbbreviation": "AGRIS", "theNameOfTheBank": "Bank IBK Indonesia"},
    {"bankCode": "494", "bankAbbreviation": "AGRONIAGA", "theNameOfTheBank": "Bank Agroniaga"},
    {"bankCode": "466", "bankAbbreviation": "ANDARA", "theNameOfTheBank": "Bank Andara"},
    {"bankCode": "531", "bankAbbreviation": "ANGLOMAS", "theNameOfTheBank": "Anglomas International Bank"},
    {"bankCode": "061", "bankAbbreviation": "ANZ", "theNameOfTheBank": "Bank ANZ Indonesia"},
    {"bankCode": "020", "bankAbbreviation": "ARTA_NIAGA_KENCANA", "theNameOfTheBank": "Bank Arta Niaga Kencana"},
    {"bankCode": "037", "bankAbbreviation": "ARTHA", "theNameOfTheBank": "Bank Artha Graha Internasional"},
    {"bankCode": "542", "bankAbbreviation": "ARTOS", "theNameOfTheBank": "Bank ARTOS/ Bank Jago"},
    {"bankCode": "129", "bankAbbreviation": "BALI", "theNameOfTheBank": "BPD Bali"},
    {"bankCode": "459", "bankAbbreviation": "BISNIS_INTERNASIONAL", "theNameOfTheBank": "Bank Bisnis Internasional"},
    {"bankCode": "040", "bankAbbreviation": "BANGKOK", "theNameOfTheBank": "Bangkok Bank"},
    {"bankCode": "558", "bankAbbreviation": "BANTEN", "theNameOfTheBank": "BPD Banten"},
    {"bankCode": "014", "bankAbbreviation": "BCA", "theNameOfTheBank": "Bank Central Asia(BCA)"},
    {"bankCode": "536", "bankAbbreviation": "BCA_SYR", "theNameOfTheBank": "Bank Central Asia (BCA) Syariah"},
    {"bankCode": "133", "bankAbbreviation": "BENGKULU", "theNameOfTheBank": "Bank Bengkulu"},
    {"bankCode": "110", "bankAbbreviation": "BJB", "theNameOfTheBank": "Bank Jawa Barat(BJB)"},
    {"bankCode": "425", "bankAbbreviation": "BJB_SYR", "theNameOfTheBank": "Bank BJB Syariah"},
    {"bankCode": "009", "bankAbbreviation": "BNI", "theNameOfTheBank": "Bank Negara Indonesia(BNI)"},
    {"bankCode": "427", "bankAbbreviation": "BNI_SYR", "theNameOfTheBank": "Bank BNI Syariah"},
    {"bankCode": "069", "bankAbbreviation": "BOC", "theNameOfTheBank": "BANK OF CHINA LIMITED"},
    {"bankCode": "002", "bankAbbreviation": "BRI", "theNameOfTheBank": "Bank Rakyat Indonesia(BRI)"},
    {"bankCode": "422", "bankAbbreviation": "BRI_SYR", "theNameOfTheBank": "Bank BRI Syariah"},
    {"bankCode": "1450", "bankAbbreviation": "BNP_PARIBAS", "theNameOfTheBank": "Bank BNP Paribas"},
    {"bankCode": "4510", "bankAbbreviation": "BSI", "theNameOfTheBank": "Bank Syariah Indonesia(BSI)"},
    {"bankCode": "200", "bankAbbreviation": "BTN", "theNameOfTheBank": "Bank Tabungan Negara (BTN)"},
    {"bankCode": "2000", "bankAbbreviation": "BTN_UUS", "theNameOfTheBank": "Bank Tabungan Negara (BTN) UUS"},
    {"bankCode": "213", "bankAbbreviation": "BTPN", "theNameOfTheBank": "Bank BTPN"},
    {"bankCode": "5470", "bankAbbreviation": "BTPN_SYARIAH", "theNameOfTheBank": "BTPN Syariah"},
    {"bankCode": "547", "bankAbbreviation": "BTPN_SYR", "theNameOfTheBank": "Bank BTPN Syariah"},
    {"bankCode": "441", "bankAbbreviation": "BUKOPIN", "theNameOfTheBank": "Wokee/Bukopin"},
    {"bankCode": "521", "bankAbbreviation": "BUKOPIN_SYR", "theNameOfTheBank": "Bank Bukopin Syariah"},
    {"bankCode": "076", "bankAbbreviation": "BUMI_ARTA", "theNameOfTheBank": "Bank Bumi Arta"},
    {"bankCode": "054", "bankAbbreviation": "CAPITAL", "theNameOfTheBank": "Bank Capital Indonesia"},
    {"bankCode": "949", "bankAbbreviation": "CHINATRUST", "theNameOfTheBank": "CTBC Indonesia"},
    {"bankCode": "559", "bankAbbreviation": "CNB", "theNameOfTheBank": "Centratama Nasional Bank(CNB)"},
    {"bankCode": "022", "bankAbbreviation": "CIMB", "theNameOfTheBank": "Bank CIMB Niaga"},
    {"bankCode": "0220", "bankAbbreviation": "CIMB_UUS", "theNameOfTheBank": "Bank CIMB Niaga UUS"},
    {"bankCode": "031", "bankAbbreviation": "CITIBANK", "theNameOfTheBank": "Citibank"},
    {"bankCode": "950", "bankAbbreviation": "COMMONWEALTH", "theNameOfTheBank": "Bank Commonwealth"},
    {"bankCode": "112", "bankAbbreviation": "BPD_DIY", "theNameOfTheBank": "BPD DIY"},
    {"bankCode": "011", "bankAbbreviation": "DANAMON", "theNameOfTheBank": "Bank Danamon"},
    {"bankCode": "0110", "bankAbbreviation": "DANAMON_UUS", "theNameOfTheBank": "Bank Danamon UUS"},
    {"bankCode": "046", "bankAbbreviation": "DBS", "theNameOfTheBank": "Bank DBS Indonesia"},
    {"bankCode": "526", "bankAbbreviation": "DINAR_INDONESIA", "theNameOfTheBank": "Bank Dinar Indonesia"},
    {"bankCode": "111", "bankAbbreviation": "DKI", "theNameOfTheBank": "Bank DKI"},
    {"bankCode": "778", "bankAbbreviation": "DKI_UUS", "theNameOfTheBank": "Bank DKI UUS"},
    {"bankCode": "562", "bankAbbreviation": "FAMA", "theNameOfTheBank": "Bank Fama International"},
    {"bankCode": "699", "bankAbbreviation": "EKA", "theNameOfTheBank": "Bank EKA"},
    {"bankCode": "161", "bankAbbreviation": "GANESHA", "theNameOfTheBank": "Bank Ganesha"},
    {"bankCode": "484", "bankAbbreviation": "HANA", "theNameOfTheBank": "LINE Bank/KEB Hana"},
    {"bankCode": "567", "bankAbbreviation": "HARDA_INTERNASIONAL", "theNameOfTheBank": "Allo Bank/Bank Harda Internasional"},
    {"bankCode": "2120", "bankAbbreviation": "HIMPUNAN_SAUDARA", "theNameOfTheBank": "Bank Himpunan Saudara 1906"},
    {"bankCode": "041", "bankAbbreviation": "HSBC", "theNameOfTheBank": "HSBC"},
    {"bankCode": "164", "bankAbbreviation": "ICBC", "theNameOfTheBank": "Bank ICBC Indonesia"},
    {"bankCode": "513", "bankAbbreviation": "INA_PERDANA", "theNameOfTheBank": "Bank Ina Perdana"},
    {"bankCode": "555", "bankAbbreviation": "INDEX_SELINDO", "theNameOfTheBank": "Bank Index Selindo"},
    {"bankCode": "146", "bankAbbreviation": "INDIA", "theNameOfTheBank": "Bank of India Indonesia"},
    {"bankCode": "115", "bankAbbreviation": "JAMBI", "theNameOfTheBank": "Bank Jambi"},
    {"bankCode": "472", "bankAbbreviation": "JASA_JAKARTA", "theNameOfTheBank": "Bank Jasa Jakarta"},
    {"bankCode": "113", "bankAbbreviation": "JAWA_TENGAH", "theNameOfTheBank": "Bank Jateng"},
    {"bankCode": "114", "bankAbbreviation": "JATIM", "theNameOfTheBank": "Bank Jatim"},
    {"bankCode": "095", "bankAbbreviation": "JTRUST", "theNameOfTheBank": "Bank JTrust Indonesia"},
    {"bankCode": "123", "bankAbbreviation": "KALIMANTAN_BARAT", "theNameOfTheBank": "BPD Kalimantan Barat(Kalbar)"},
    {"bankCode": "1230", "bankAbbreviation": "KALIMANTAN_BARAT_UUS", "theNameOfTheBank": "BPD Kalimantan Barat UUS"},
    {"bankCode": "122", "bankAbbreviation": "KALIMANTAN_SELATAN", "theNameOfTheBank": "BPD Kalimantan Selatan(Kalsel)"},
    {"bankCode": "1220", "bankAbbreviation": "KALIMANTAN_SELATAN_UUS", "theNameOfTheBank": "BPD Kalimantan Selatan UUS"},
    {"bankCode": "125", "bankAbbreviation": "KALIMANTAN_TENGAH", "theNameOfTheBank": "BPD Kalimantan Tengah (Kalteng)"},
    {"bankCode": "124", "bankAbbreviation": "KALIMANTAN_TIMUR", "theNameOfTheBank": "BPD Kalimantan Timur"},
    {"bankCode": "1240", "bankAbbreviation": "KALIMANTAN_TIMUR_UUS", "theNameOfTheBank": "BPD Kalimantan Timur UUS"},
    {"bankCode": "535", "bankAbbreviation": "KESEJAHTERAAN_EKONOMI", "theNameOfTheBank": "Seabank/Bank Kesejahteraan Ekonomi(BKE)"},
    {"bankCode": "121", "bankAbbreviation": "LAMPUNG", "theNameOfTheBank": "BPD Lampung"},
    {"bankCode": "131", "bankAbbreviation": "MALUKU", "theNameOfTheBank": "Bank Maluku"},
    {"bankCode": "008", "bankAbbreviation": "MANDIRI", "theNameOfTheBank": "Bank Mandiri"},
    {"bankCode": "564", "bankAbbreviation": "MANTAP", "theNameOfTheBank": "Bank MANTAP"},
    {"bankCode": "548", "bankAbbreviation": "MULTI_ARTA_SENTOSA", "theNameOfTheBank": "Bank Multi Arta Sentosa(MAS)"},
    {"bankCode": "157", "bankAbbreviation": "MASPION", "theNameOfTheBank": "Bank Maspion Indonesia"},
    {"bankCode": "097", "bankAbbreviation": "MAYAPADA", "theNameOfTheBank": "Bank Mayapada"},
    {"bankCode": "016", "bankAbbreviation": "MAYBANK", "theNameOfTheBank": "Bank Maybank"},
    {"bankCode": "947", "bankAbbreviation": "MAYBANK_SYR", "theNameOfTheBank": "Bank Maybank Syariah Indonesia"},
    {"bankCode": "553", "bankAbbreviation": "MAYORA", "theNameOfTheBank": "Bank Mayora Indonesia"},
    {"bankCode": "426", "bankAbbreviation": "MEGA", "theNameOfTheBank": "Bank Mega"},
    {"bankCode": "506", "bankAbbreviation": "MEGA_SYR", "theNameOfTheBank": "Bank Mega Syariah"},
    {"bankCode": "151", "bankAbbreviation": "MESTIKA_DHARMA", "theNameOfTheBank": "Bank Mestika Dharma"},
    {"bankCode": "485", "bankAbbreviation": "MNC_INTERNASIONAL", "theNameOfTheBank": "Motion/Bank MNC Internasional"},
    {"bankCode": "147", "bankAbbreviation": "MUAMALAT", "theNameOfTheBank": "Bank Muamalat Indonesia"},
    {"bankCode": "491", "bankAbbreviation": "MITRA_NIAGA", "theNameOfTheBank": "Bank Mitra Niaga"},
    {"bankCode": "048", "bankAbbreviation": "MIZUHO", "theNameOfTheBank": "Bank Mizuho Indonesia"},
    {"bankCode": "503", "bankAbbreviation": "NATIONALNOBU", "theNameOfTheBank": "Bank National Nobu"},
    {"bankCode": "128", "bankAbbreviation": "NUSA_TENGGARA_BARAT", "theNameOfTheBank": "BPD Nusa Tenggara Barat(NTB)"},
    {"bankCode": "1280", "bankAbbreviation": "NUSA_TENGGARA_BARAT_UUS", "theNameOfTheBank": "BPD Nusa Tenggara Barat (NTB) UUS"},
    {"bankCode": "130", "bankAbbreviation": "NUSA_TENGGARA_TIMUR", "theNameOfTheBank": "BPD Nusa Tenggara Timur(NTT)"},
    {"bankCode": "145", "bankAbbreviation": "NUSANTARA_PARAHYANGAN", "theNameOfTheBank": "Bank Nusantara Parahyangan"},
    {"bankCode": "028", "bankAbbreviation": "OCBC", "theNameOfTheBank": "Bank OCBC NISP"},
    {"bankCode": "0280", "bankAbbreviation": "OCBC_UUS", "theNameOfTheBank": "Bank OCBC NISP UUS"},
    {"bankCode": "019", "bankAbbreviation": "PANIN", "theNameOfTheBank": "Bank Panin"},
    {"bankCode": "517", "bankAbbreviation": "PANIN_SYR", "theNameOfTheBank": "Panin Dubai Syariah"},
    {"bankCode": "132", "bankAbbreviation": "PAPUA", "theNameOfTheBank": "Bank Papua"},
    {"bankCode": "013", "bankAbbreviation": "PERMATA", "theNameOfTheBank": "Bank Permata"},
    {"bankCode": "0130", "bankAbbreviation": "PERMATA_UUS", "theNameOfTheBank": "Bank Permata UUS"},
    {"bankCode": "520", "bankAbbreviation": "PRIMA_MASTER", "theNameOfTheBank": "Bank Prima Master"},
    {"bankCode": "167", "bankAbbreviation": "QNB_KESAWAN", "theNameOfTheBank": "QNB KESAWAN"},
    {"bankCode": "1670", "bankAbbreviation": "QNB_INDONESIA", "theNameOfTheBank": "QNB Indonesia"},
    {"bankCode": "5260", "bankAbbreviation": "OKE", "theNameOfTheBank": "Bank Oke Indonesia"},
    {"bankCode": "089", "bankAbbreviation": "RABOBANK", "theNameOfTheBank": "Rabobank International Indonesia"},
    {"bankCode": "047", "bankAbbreviation": "RESONA", "theNameOfTheBank": "Bank Resona Perdania"},
    {"bankCode": "119", "bankAbbreviation": "RIAU_DAN_KEPRI", "theNameOfTheBank": "BPD Riau Dan Kepri"},
    {"bankCode": "1190", "bankAbbreviation": "RIAU_DAN_KEPRI_UUS", "theNameOfTheBank": "BPD Riau Dan Kepri UUS"},
    {"bankCode": "523", "bankAbbreviation": "SAHABAT_SAMPOERNA", "theNameOfTheBank": "Bank Sahabat Sampoerna"},
    {"bankCode": "498", "bankAbbreviation": "SBI_INDONESIA", "theNameOfTheBank": "Bank SBI Indonesia"},
    {"bankCode": "152", "bankAbbreviation": "SHINHAN", "theNameOfTheBank": "Bank Shinhan Indonesia"},
    {"bankCode": "153", "bankAbbreviation": "SINARMAS", "theNameOfTheBank": "Bank Sinarmas"},
    {"bankCode": "050", "bankAbbreviation": "STANDARD_CHARTERED", "theNameOfTheBank": "Standard Chartered Bank"},
    {"bankCode": "134", "bankAbbreviation": "SULAWESI", "theNameOfTheBank": "Bank Sulteng"},
    {"bankCode": "135", "bankAbbreviation": "SULAWESI_TENGGARA", "theNameOfTheBank": "Bank Sultra"},
    {"bankCode": "126", "bankAbbreviation": "SULSELBAR", "theNameOfTheBank": "Bank Sulselbar"},
    {"bankCode": "1260", "bankAbbreviation": "SULSELBAR_UUS", "theNameOfTheBank": "Bank Sulselbar UUS"},
    {"bankCode": "127", "bankAbbreviation": "SULUT", "theNameOfTheBank": "BPD Sulawesi Utara(SulutGo)"},
    {"bankCode": "118", "bankAbbreviation": "SUMATERA_BARAT", "theNameOfTheBank": "BPD Sumatera Barat"},
    {"bankCode": "1180", "bankAbbreviation": "SUMATERA_BARAT_UUS", "theNameOfTheBank": "BPD Sumatera Barat UUS"},
    {"bankCode": "120", "bankAbbreviation": "SUMSEL_DAN_BABEL", "theNameOfTheBank": "BPD Sumsel Babel"},
    {"bankCode": "1200", "bankAbbreviation": "SUMSEL_DAN_BABEL_UUS", "theNameOfTheBank": "Bank Sumsel Babel UUS"},
    {"bankCode": "117", "bankAbbreviation": "SUMUT", "theNameOfTheBank": "Bank Sumut"},
    {"bankCode": "1170", "bankAbbreviation": "SUMUT_UUS", "theNameOfTheBank": "Bank Sumut UUS"},
    {"bankCode": "1530", "bankAbbreviation": "SINARMAS_UUS", "theNameOfTheBank": "Bank Sinarmas UUS"},
    {"bankCode": "045", "bankAbbreviation": "MITSUI", "theNameOfTheBank": "Bank Sumitomo Mitsui Indonesia"},
    {"bankCode": "451", "bankAbbreviation": "MANDIRI_SYR", "theNameOfTheBank": "Bank Syariah Mandiri(BSM)"},
    {"bankCode": "042", "bankAbbreviation": "TOKYO", "theNameOfTheBank": "Bank of Tokyo"},
    {"bankCode": "023", "bankAbbreviation": "UOB", "theNameOfTheBank": "TMRW/Bank UOB Indonesia"},
    {"bankCode": "566", "bankAbbreviation": "VICTORIA_INTERNASIONAL", "theNameOfTheBank": "Bank Victoria International"},
    {"bankCode": "405", "bankAbbreviation": "VICTORIA_SYR", "theNameOfTheBank": "Bank Victoria Syariah"},
    {"bankCode": "212", "bankAbbreviation": "WOORI", "theNameOfTheBank": "Bank Woori Saudara"},
    {"bankCode": "490", "bankAbbreviation": "YUDHA_BHAKTI", "theNameOfTheBank": "Neo Commerce/Bank Yudha Bhakti(BNC)"},
    {"bankCode": "1120", "bankAbbreviation": "DAERAH_ISTIMEWA_UUS", "theNameOfTheBank": "BPD_Daerah_Istimewa_Yogyakarta_(DIY)"},
    {"bankCode": "5590", "bankAbbreviation": "CENTRATAMA", "theNameOfTheBank": "Bank Centratama"},
    {"bankCode": "088", "bankAbbreviation": "CCB", "theNameOfTheBank": "CCB Indonesia"},
    {"bankCode": "067", "bankAbbreviation": "DEUTSCHE", "theNameOfTheBank": "Deutsche Bank"},
    {"bankCode": "032", "bankAbbreviation": "JPMORGAN", "theNameOfTheBank": "JPMORGAN CHASE BANK"},
    {"bankCode": "5640", "bankAbbreviation": "MANDIRI_TASPEN", "theNameOfTheBank": "Bank Mandiri Taspen Pos"},
    {"bankCode": "501", "bankAbbreviation": "RBS", "theNameOfTheBank": "Royal Bank of Scotland (RBS)"},
    {"bankCode": "10001", "bankAbbreviation": "OVO", "theNameOfTheBank": "OVO"},
    {"bankCode": "10002", "bankAbbreviation": "DANA", "theNameOfTheBank": "DANA"},
    {"bankCode": "10003", "bankAbbreviation": "GOPAY", "theNameOfTheBank": "GOPAY"},
    {"bankCode": "10006", "bankAbbreviation": "MULTICOR", "theNameOfTheBank": "Bank MULTICOR"},
    {"bankCode": "10008", "bankAbbreviation": "SHOPEEPAY", "theNameOfTheBank": "SHOPEEPAY"},
    {"bankCode": "10009", "bankAbbreviation": "LINKAJA", "theNameOfTheBank": "LINKAJA"},
    {"bankCode": "10010", "bankAbbreviation": "MUTIARA", "theNameOfTheBank": "Bank MUTIARA"},
]