JAYAPAY_PH_PAYOUT_BANKS = [
    {"bankCode": "GCASH", "bankName": "Gcash"},
    {"bankCode": "PAY_MAYA", "bankName": "PayMaya Philippines"},
    {"bankCode": "BPI_BANK", "bankName": "BPI Bank"},
    {"bankCode": "BDO_UNIBANK", "bankName": "BDO Unibank"},
    {"bankCode": "MBTC", "bankName": "Metropolitan Bank and Trust Co"},
    {"bankCode": "LANDBANK", "bankName": "LANDBANK / OFBank"},
    {"bankCode": "SECURITY_BANK", "bankName": "Security Bank Corporation"},
    {"bankCode": "UNION_BANK", "bankName": "Union Bank of the Philippines"},
    {"bankCode": "PHILIPPINE_NATIONAL_BANK", "bankName": "Philippine National Bank"},
    {"bankCode": "CBC", "bankName": "China Banking Corporation"},
    {"bankCode": "EWBC", "bankName": "East West Banking Corporation"},
    {"bankCode": "RCBC", "bankName": "RCBC/DiskarTech"},
    {"bankCode": "UCPB", "bankName": "United Coconut Planters Bank (UCPB)"},
    {"bankCode": "PSB", "bankName": "Philippine Savings Bank"},
    {"bankCode": "AUBC", "bankName": "Asia United Bank Corporation"},
    {"bankCode": "PHILIPPINE_COMMUNICATIONS", "bankName": "Philippine Bank of Communications"},
    {"bankCode": "DEVELOPMENT_PHILIPPINES", "bankName": "Development Bank of the Philippines"},
    {"bankCode": "ROBINSONS_BANK_CORPORATION", "bankName": "Robinsons Bank Corporation"},
    {"bankCode": "ALLBANK", "bankName": "ALLBANK(A Thirft Bank)"},
    {"bankCode": "BANGKO", "bankName": "Bangko Mabuhay"},
    {"bankCode": "BANK_OF_CHINA", "bankName": "Bank of China"},
    {"bankCode": "BANK_OF_COMMERCE", "bankName": "Bank of Commerce"},
    {"bankCode": "BDO", "bankName": "BDO NeTwork Bank"},
    {"bankCode": "BRB", "bankName": "Binangonan Rural Bank / BRBDigital"},
    {"bankCode": "CAMALIG_BANK", "bankName": "Camalig Bank"},
    {"bankCode": "BANK_CARD_BANK", "bankName": "Bank CARD Bank"},
    {"bankCode": "CARD_SME_BANK", "bankName": "CARD SME Bank"},
    {"bankCode": "CEBUANA_LHUILLIER_BANK", "bankName": "Cebuana Lhuillier Bank / Cebuana Xpress"},
    {"bankCode": "CHINA_BANK_SAVINGS", "bankName": "China Bank Savings"},
    {"bankCode": "CIMB_PHILIPPINES_INC", "bankName": "CIMB Philippines, Inc."},
    {"bankCode": "CIS_BAYAD_CENTER_BAYAD", "bankName": "CIS Bayad Center / Bayad"},
    {"bankCode": "CTBC", "bankName": "CTBC Bank (Philippines) Corporation"},
    {"bankCode": "DCPAY", "bankName": "DCPay / COINS.PH"},
    {"bankCode": "DCDB", "bankName": "Dumaguete City Development Bank"},
    {"bankCode": "DUNGGANON_BANK", "bankName": "Dungganon Bank"},
    {"bankCode": "EWRB", "bankName": "East West Rural Bank / Komo"},
    {"bankCode": "ESB", "bankName": "Equicom Savings Bank, Inc."},
    {"bankCode": "GOTYME_BANK", "bankName": "GoTyme Bank"},
    {"bankCode": "GRABPAY", "bankName": "GrabPay"},
    {"bankCode": "I_REMIT_ICASH", "bankName": "I-Remit / iCASH"},
    {"bankCode": "INFOSERVE_NATIONLINK", "bankName": "Infoserve / Nationlink"},
    {"bankCode": "ISLA_BANK", "bankName": "ISLA Bank"},
    {"bankCode": "LEGAZPI_SAVING_BANK", "bankName": "Legazpi Saving Bank"},
    {"bankCode": "LUZON_DEVELOPMENT_BANK", "bankName": "Luzon Development Bank"},
    {"bankCode": "MBSMB", "bankName": "Malayan Bank Savings and Mortgage Bank, Inc."},
    {"bankCode": "ZYBI_TECH", "bankName": "Zybi Tech Inc. / JuanCash"},
    {"bankCode": "MAYA_BANK_", "bankName": "Maya Bank, Inc."},
    {"bankCode": "MAYBANK_PHILIPPNIES", "bankName": "Maybank Philippnies"},
    {"bankCode": "MINDANAO", "bankName": "Mindanao Consolidated CoopBank"},
    {"bankCode": "NETBANK", "bankName": "Netbank"},
    {"bankCode": "OMNI_PAY", "bankName": "OmniPay, Inc."},
    {"bankCode": "PALAWANPAY", "bankName": "PalawanPay"},
    {"bankCode": "PRB", "bankName": "Partner Rural Bank (Cotabato), Inc."},
    {"bankCode": "PHILIPPINE_BUSINESS_BANK", "bankName": "Philippine Business Bank"},
    {"bankCode": "PHILIPPINE_TRUST_COMPANY", "bankName": "Philippine Trust Company"},
    {"bankCode": "PRODUCERS_BANK", "bankName": "Producers Bank"},
    {"bankCode": "QUEENBANK", "bankName": "Queenbank"},
    {"bankCode": "QCRB", "bankName": "Quezon Capital Rural Bank"},
    {"bankCode": "RBG", "bankName": "Rural Bank of Guinobatan / Asenso"},
    {"bankCode": "SEABANK", "bankName": "Seabank"},
    {"bankCode": "SHOPEEPAY", "bankName": "ShopeePay"},
    {"bankCode": "STANDARD_CHARTERED_BANK", "bankName": "Standard Chartered Bank"},
    {"bankCode": "STARPAY", "bankName": "Starpay"},
    {"bankCode": "STERLING_BANK_OF_ASIA", "bankName": "Sterling Bank of Asia"},
    {"bankCode": "SUN_SAVINGS_BANK", "bankName": "Sun Savings Bank"},
    {"bankCode": "TAYOCASH", "bankName": "TayoCash"},
    {"bankCode": "TRAXIONPAY_DIGICOOP_COOPNET", "bankName": "TraxionPay/DigiCOOP/COOPNET"},
    {"bankCode": "UNION_DIGITAL_BANK", "bankName": "UnionDigital Bank"},
    {"bankCode": "UCPB_SAVINGS_BANK", "bankName": "UCPB Savings Bank"},
    {"bankCode": "USSC_MONET_SERVICES", "bankName": "USSC Monet Services"},
    {"bankCode": "WEALTH_DEVELOPMENT_BANK", "bankName": "Wealth Development Bank"},
    {"bankCode": "GCASH_WAP", "bankName": "GCASH Imitation of native"},
    {"bankCode": "MAYA_WAP", "bankName": "MAYA Imitation of native"},
    {"bankCode": "MAYA_BANK", "bankName": "Maya Bank, Inc."},
]

