PPAYPROS_PAYOUT_CODES = [
    {"code": "day", "name": "day", "category": "wallet"},
    {"code": "gopay", "name": "gopay", "category": "wallet"},
    {"code": "linkaja", "name": "linkaja", "category": "wallet"},
    {"code": "OV", "name": "THIS", "category": "wallet"},
    {"code": "shopeepay", "name": "shopeepay", "category": "wallet"},
    {"code": "ACEH", "name": "BPD ACEH", "category": "bank"},
    {"code": "AGRONIAGA", "name": "BANK AGRO NIAGA", "category": "bank"},
    {"code": "COMMERCIAL_PROPERTIES", "name": "BANK ARTA NIAGA KENCANA", "category": "bank"},
    {"code": "ARTHA", "name": "BANK ARTHA GRAHA", "category": "bank"},
    {"code": "Converter", "name": "BANK ARTOS IN", "category": "bank"},
    {"code": "BALI", "name": "BPD BALI", "category": "bank"},
    {"code": "BAML", "name": "BANK OF AMERICA", "category": "bank"},
    {"code": "BANK_ABN", "name": "BANK ABN AMRO", "category": "bank"},
    {"code": "BANK_AKITA", "name": "BANK AKITA", "category": "bank"},
    {"code": "BANK_ANTAR", "name": "INTER-REGIONAL BANK", "category": "bank"},
    {"code": "BANK_BUANA", "name": "BANK BUANA IND", "category": "bank"},
    {"code": "BANK_BUMIPUTERA", "name": "BUMIPUTERA BANK", "category": "bank"},
    {"code": "BANK_COMP", "name": "THE BANGKOK BANK COMP. LTD", "category": "bank"},
    {"code": "BANK_C_AGR", "name": "BANK CREDIT AGRICOLE INDOSUEZ", "category": "bank"},
    {"code": "BANK_DANAMON", "name": "KOREA EXCHANGE BANK DANAMON", "category": "bank"},
    {"code": "BANK_EXEC", "name": "EXECUTIVE BANK", "category": "bank"},
    {"code": "BANK_FINCONESIA", "name": "BANK FINCONESIA", "category": "bank"},
    {"code": "BANK_HAGA", "name": "BANK HAGA", "category": "bank"},
    {"code": "BANK_HAGAKITA", "name": "BANK HAGAKITA", "category": "bank"},
    {"code": "BANK_HARM", "name": "BANK HARMONI INTERNATIONAL", "category": "bank"},
    {"code": "BANK_HIM", "name": "BANK ASSOCIATION OF BROTHERS 1906, TBK.", "category": "bank"},
    {"code": "BANK_IFI", "name": "BANK IFI", "category": "bank"},
    {"code": "BANK_INA", "name": "BANK INA PERDANA", "category": "bank"},
    {"code": "BANK_INDOMONEX", "name": "BANK INDOMONEX", "category": "bank"},
    {"code": "BANK_ING", "name": "ING INDONESIA BANK", "category": "bank"},
    {"code": "BANK_WATER", "name": "BANK JABAR BANTEN", "category": "bank"},
    {"code": "BANK_JATENG", "name": "BANK OF CENTRAL JAVA", "category": "bank"},
    {"code": "BANK_JATIM", "name": "BANK OF JATIM", "category": "bank"},
    {"code": "BANK_KEPPEL", "name": "KEPPEL TATLEE BUANA BANK", "category": "bank"},
    {"code": "BANK_LIPPO", "name": "LIPPO BANK", "category": "bank"},
    {"code": "BANK_MAYBANK", "name": "BANK MAYBANK INDOCORP", "category": "bank"},
    {"code": "BANK_MERIN", "name": "MERINCORP BANK", "category": "bank"},
    {"code": "BANK_MITRAN", "name": "MITRANIAG BANK", "category": "bank"},
    {"code": "BANK_MUL", "name": "BANK MULTICOR TBK.", "category": "bank"},
    {"code": "BANK_NAGARI", "name": "BANK NAGARI", "category": "bank"},
    {"code": "BANK_NOBU", "name": "BANK DIPO INTERNATIONAL", "category": "bank"},
    {"code": "BANK_NTT", "name": "BANK NTT", "category": "bank"},
    {"code": "BANK_PERSY", "name": "STATE BANK OF INDONESIA", "category": "bank"},
    {"code": "BANK_SULTRA", "name": "BANK SULTRA", "category": "bank"},
    {"code": "BANK_SWADESI", "name": "SWADESI BANK", "category": "bank"},
    {"code": "BANK_SWAGUNA", "name": "SELF-SUFFICIENT BANK", "category": "bank"},
    {"code": "BANK_TOKYO", "name": "THE BANK OF TOKYO MITSUBISHI UFJ LTD", "category": "bank"},
    {"code": "BANK_UOB", "name": "BANK UOB INDONESIA", "category": "bank"},
    {"code": "BANK_VICTORIA", "name": "BANK VICTORIA INTERNATIONAL", "category": "bank"},
    {"code": "BANK_WORD", "name": "BANK WOORI INDONESIA", "category": "bank"},
    {"code": "BANK_YUDHA", "name": "BANK YUDHA BHAKTI", "category": "bank"},
    {"code": "BCA", "name": "BANK BCA", "category": "bank"},
    {"code": "BCA_SYR", "name": "BCA SYARIAH BANK", "category": "bank"},
    {"code": "BENGKULU", "name": "BANK BENGKULU", "category": "bank"},
    {"code": "INTERNATIONAL BUSINESS", "name": "INTERNATIONAL BUSINESS BANK", "category": "bank"},
    {"code": "BJB_SYR", "name": "BJB SYARIAH", "category": "bank"},
    {"code": "BNI", "name": "BANK BNI", "category": "bank"},
    {"code": "BNI_SYR", "name": "BNI SYARIAH BANK", "category": "bank"},
    {"code": "BNP_PARIBAS", "name": "BANK BNP PARIBAS INDONESIA", "category": "bank"},
    {"code": "BOC", "name": "BANK OF CHINA LIMITED", "category": "bank"},
    {"code": "BPD_BLACK", "name": "BPD KALTIM", "category": "bank"},
    {"code": "BPD_KALSEL", "name": "South Kalimantan Regional Development Bank", "category": "bank"},
    {"code": "BPD_KALTENG", "name": "Central Kalimantan Regional Development Bank", "category": "bank"},
    {"code": "BPD_NTB", "name": "NTB Regional Development Bank", "category": "bank"},
    {"code": "BRI", "name": "BANK BRI", "category": "bank"},
    {"code": "BRI_SYR", "name": "BRI SYARIAH BANK", "category": "bank"},
    {"code": "BTN", "name": "STATE SAVINGS BANK (LIMITED)", "category": "bank"},
    {"code": "BTPN_SYARIAH", "name": "BANK PURBA DANARTA", "category": "bank"},
    {"code": "BUKOPIN", "name": "BUKOPIN BANK", "category": "bank"},
    {"code": "BUMI_ARTA", "name": "BUMI ARTA BANK", "category": "bank"},
    {"code": "CAPITAL", "name": "BANK CAPITAL INDONESIA, Tbk.", "category": "bank"},
    {"code": "CCB", "name": "BANK WINDU KENTJANA", "category": "bank"},
    {"code": "CENTER", "name": "CENTRATAMA NASIONAL BANK", "category": "bank"},
    {"code": "CHINATRUST", "name": "BANK CHINA TRUST INDONESIA", "category": "bank"},
    {"code": "CIMB", "name": "CIMB BANK COMMERCE", "category": "bank"},
    {"code": "CITIBANK", "name": "CITIBANK", "category": "bank"},
    {"code": "COMMONWEALTH", "name": "BANK COMMONWEALTH", "category": "bank"},
    {"code": "SPECIAL REGION", "name": "BPD DIY", "category": "bank"},
    {"code": "DANAMON", "name": "DANAMON BANK", "category": "bank"},
    {"code": "DBS", "name": "BANK DBS INDONESIA", "category": "bank"},
    {"code": "DEUTSCHE", "name": "DEUTSCHE BANK AG.", "category": "bank"},
    {"code": "DINAR_INDONESIA", "name": "BANK DINAR INDONESIA", "category": "bank"},
    {"code": "DKI", "name": "BANK DKI", "category": "bank"},
    {"code": "EXIMBANK", "name": "INDONESIAN EXPORT BANK", "category": "bank"},
    {"code": "STRUGGLE", "name": "FAMA INTERNATIONAL BANK", "category": "bank"},
    {"code": "FT", "name": "Alfamart", "category": "bank"},
    {"code": "GANESHA", "name": "BANK GANESHA", "category": "bank"},
    {"code": "WORK", "name": "BANK HANA", "category": "bank"},
    {"code": "HARDA_INTERNATIONAL", "name": "BANK HARDA", "category": "bank"},
    {"code": "HSBC", "name": "BANK HSBC", "category": "bank"},
    {"code": "ICBC", "name": "BANK ICBC", "category": "bank"},
    {"code": "INDEX_SELINDO", "name": "BANK INDEX SELINDO", "category": "bank"},
    {"code": "JAMBI", "name": "JAMBI Regional Development Bank", "category": "bank"},
    {"code": "SERVICES_JAKARTA", "name": "JAKARTA SERVICE BANK", "category": "bank"},
    {"code": "JPMORGAN", "name": "JP. MORGAN CHASE BANK", "category": "bank"},
    {"code": "JTRUST", "name": "BANK JTRUST", "category": "bank"},
    {"code": "WEST KALIMANTAN", "name": "BPD WEST KALIMANTAN", "category": "bank"},
    {"code": "ECONOMIC WELFARE", "name": "ECONOMIC BANK", "category": "bank"},
    {"code": "LAMPUNG", "name": "BANK LAMPUNG", "category": "bank"},
    {"code": "MALUKU", "name": "BANK OF MALUKU", "category": "bank"},
    {"code": "INDEPENDENT", "name": "INDEPENDENT", "category": "bank"},
    {"code": "MANDIRI_SYR", "name": "MANDIRI SYARIAH BANK", "category": "bank"},
    {"code": "MANDIRI_TASPEN", "name": "BANK SINAR HARAPAN BALI", "category": "bank"},
    {"code": "MASPION", "name": "MASPION BANK", "category": "bank"},
    {"code": "MAYAPADA", "name": "MAYAPADA BANK", "category": "bank"},
    {"code": "MAYBANK", "name": "BANK MAYBANK", "category": "bank"},
    {"code": "MAYOR", "name": "BANK MAYORA", "category": "bank"},
    {"code": "MEGA", "name": "MEGA BANK", "category": "bank"},
    {"code": "MEGA_SYR", "name": "MEGA SYARIAH BANK", "category": "bank"},
    {"code": "MESTIKA_DHARMA", "name": "BANK OF MESTICA", "category": "bank"},
    {"code": "MITSUI", "name": "BANK SUMITOMO MITSUI INDONESIA", "category": "bank"},
    {"code": "MIZUHO", "name": "MIZUHO INDONESIA BANK", "category": "bank"},
    {"code": "TRANSACTIONS", "name": "BANK MUAMALAT", "category": "bank"},
    {"code": "MULTI_ARTA_SENTOSA", "name": "MULTI ARTA SENTOSA BANK", "category": "bank"},
    {"code": "NATIONALNOBU", "name": "BANK NOBU", "category": "bank"},
    {"code": "NUSANTARA_PARAHYANGAN", "name": "BANK NUSANTARA PARAHYANGAN", "category": "bank"},
    {"code": "OCBC", "name": "BANK NISP", "category": "bank"},
    {"code": "GOOD", "name": "ANDARA BANK", "category": "bank"},
    {"code": "I PUT", "name": "BANK PAN", "category": "bank"},
    {"code": "HARVEST_SYR", "name": "PANIN DUBAI SYARIAH BANK", "category": "bank"},
    {"code": "PAPUA", "name": "Papua Regional Representative Council", "category": "bank"},
    {"code": "GEM", "name": "PERMATA BANK", "category": "bank"},
    {"code": "PRIMA_MASTER", "name": "PRIMA MASTER BANK", "category": "bank"},
    {"code": "QNB_INDONESIA", "name": "KESAWAN BANK", "category": "bank"},
    {"code": "RABOBANK", "name": "RABOBANK INTERNATIONAL INDONESIA", "category": "bank"},
    {"code": "RESONATE", "name": "RESONA PERDANIA BANK", "category": "bank"},
    {"code": "RIAU AND KEPRI", "name": "BANK OF RIAU", "category": "bank"},
    {"code": "ROYAL", "name": "BANK ROYAL INDONESIA", "category": "bank"},
    {"code": "SHINHAN", "name": "BANK METRO EXPRESS", "category": "bank"},
    {"code": "SINARMA_NEW", "name": "SINARMAS BANK", "category": "bank"},
    {"code": "STANDARD_CHARTERED", "name": "STANDARD CHARTERED BANK", "category": "bank"},
    {"code": "SULAWESI", "name": "BPD CENTRAL SULAWESI", "category": "bank"},
    {"code": "South and West Sulawesi", "name": "South Sulawesi Regional Development Bank", "category": "bank"},
    {"code": "SUMSEL_AND_BABEL", "name": "BANK OF SOUTH SUMATRA", "category": "bank"},
    {"code": "NORTH SUMATRA", "name": "BANK OF SUMUT", "category": "bank"},
    {"code": "NATIONAL RETIREMENT SAVINGS", "name": "NATIONAL PENSION SAVINGS BANK", "category": "bank"},
    {"code": "ALLO_BANK_INDONESIA", "name": "PT ALLO BANK INDONESIA", "category": "bank"},
    {"code": "BANK_ACEH_SYARIAH", "name": "BANK ACEH SYARIAH", "category": "bank"},
    {"code": "BANK_ALADIN", "name": "BANK ALADIN", "category": "bank"},
    {"code": "BANK_AMAR_INDONESIA", "name": "BANK AMAR INDONESIA", "category": "bank"},
    {"code": "BANK_ANZ", "name": "BANK ANZ", "category": "bank"},
    {"code": "BANK_BANTEN", "name": "BANK BANTEN", "category": "bank"},
    {"code": "BANK_BJB", "name": "BANK BJB", "category": "bank"},
    {"code": "BANK_BPR_KS", "name": "BANK BPR KS", "category": "bank"},
    {"code": "BANK_BTN_SYARIAH", "name": "BTN SYARIAH BANK", "category": "bank"},
    {"code": "BANK_BUKOPIN_SYARIAH", "name": "BUKOPIN SYARIAH BANK", "category": "bank"},
    {"code": "BANK_CHINA_CONSTRUCTION", "name": "PT. BANK CHINA CONSTRUCTION", "category": "bank"},
    {"code": "BANK_CIMB_SHARIA_TRADE", "name": "CIMB BANK SHARIA BUSINESS", "category": "bank"},
    {"code": "BANK_DANAMON_SYARIAH", "name": "BANK DANAMON SYARIAH", "category": "bank"},
    {"code": "BANK_DIGITAL_BCA", "name": "BANK DIGITAL BCA", "category": "bank"},
    {"code": "BANK_DKI_SYARIAH", "name": "DKI SYARIAH BANK", "category": "bank"},
    {"code": "BANK_EKA", "name": "BANK EKA", "category": "bank"},
    {"code": "BANK_IBK_INDONESIA", "name": "PT. BANK IBK INDONESIA", "category": "bank"},
    {"code": "BANK_INDEX", "name": "BANK INDEX", "category": "bank"},
    {"code": "BANK_INTERIM_INDONESIA", "name": "INTERIM BANK OF INDONESIA", "category": "bank"},
    {"code": "BANK_JAGO", "name": "BANK JAGO", "category": "bank"},
    {"code": "BANK_JAGO_UU_SHARIA", "name": "BANK JAGO SYARIAH LAW", "category": "bank"},
    {"code": "BANK_JATENG_SYARIAH", "name": "BANK JATENG SYARIAH", "category": "bank"},
    {"code": "BANK_JATIM_SYARIAH", "name": "JATIM SYARIAH BANK", "category": "bank"},
    {"code": "BANK_JTRUST_INDONESIA", "name": "BANK JTRUST INDONESIA", "category": "bank"},
    {"code": "BANK_KALBAR", "name": "BANK OF KALBAR", "category": "bank"},
    {"code": "BANK_KALBAR_SYARIAH", "name": "WEST KALIMANTAN SYARIAH BANK", "category": "bank"},
    {"code": "BANK_KALTENG", "name": "BANK OF CENTRAL KALTENG", "category": "bank"},
    {"code": "BANK_KB_BUKOPIN", "name": "KB BUKOPIN BANK", "category": "bank"},
    {"code": "BANK_KEB_HANA", "name": "KEB HANA BANK", "category": "bank"},
    {"code": "BANK_Krom_Indonesia", "name": "Bank Chrome Indonesia", "category": "bank"},
    {"code": "BANK_MAS", "name": "BANK MAS", "category": "bank"},
    {"code": "BANK_MAYBANK_SHARIAH_LAW", "name": "MAYBANK BANK SHARIAH LAW", "category": "bank"},
    {"code": "INTERNATIONAL MNC BANK", "name": "MNC INTERNATIONAL BANK", "category": "bank"},
    {"code": "SHARIA_STATE_BANK", "name": "SHARIAH STATE BANK", "category": "bank"},
    {"code": "NANO_SYARIAH_BANK", "name": "PT BANK NANO SYARIAH", "category": "bank"},
    {"code": "BANK_NEO_COMMERCE", "name": "BANK NEO COMMERCE", "category": "bank"},
    {"code": "BANK_OF_CHINA_HKG", "name": "BANK OF CHINA (HKG)", "category": "bank"},
    {"code": "BANK_OF_INDIA_INDONESIA", "name": "BANK OF INDIA INDONESIA", "category": "bank"},
    {"code": "BANK_ONB_INDONESIA", "name": "BANK ONB INDONESIA", "category": "bank"},
    {"code": "BANK_PERMATA_SYARIAH", "name": "PERMATA SYARIAH BANK", "category": "bank"},
    {"code": "BANK_RAYA_INDONESIA", "name": "BANK RAYA INDONESIA", "category": "bank"},
    {"code": "BANK_SAHABAT_SAMPOERNA", "name": "SAMPOERNA FRIENDLY BANK", "category": "bank"},
    {"code": "BANK_SBIINDONESIA", "name": "BANK SBI INDONESIA", "category": "bank"},
    {"code": "BANK_SEABANK_INDONESIA", "name": "SEABANK INDONESIA BANK", "category": "bank"},
    {"code": "BANK_SMBC_INDONESIA_TBK", "name": "PT BANK SMBC INDONESIA TBK", "category": "bank"},
    {"code": "BANK_SUMSEL_BABEL_SYARIAH", "name": "BANK SUMSEL BABEL SYARIAH", "category": "bank"},
    {"code": "BANK_SYARIAH_INDONESIA", "name": "INDONESIAN SHARIA BANK", "category": "bank"},
    {"code": "BANK_SulutGo", "name": "BANK SulutGo", "category": "bank"},
    {"code": "BANK_Super_indonesia", "name": "Super Bank Indonesia", "category": "bank"},
    {"code": "BANK_VICTORIA_SYARIAH", "name": "VICTORIA SYARIAH BANK", "category": "bank"},
    {"code": "BPD_DIY_SYARIAH", "name": "DIY Sharia Regional Development Bank", "category": "bank"},
    {"code": "BPD_KALSEL_SYARIAH", "name": "BPD SOUTH KALIMANTAN SYARIAH", "category": "bank"},
    {"code": "BPD_KALTIM_KALTARA", "name": "BPD KALTIM KALTAR", "category": "bank"},
    {"code": "BPD_KALTIM_SYARIAH", "name": "BPD KALTIM SYARIAH", "category": "bank"},
    {"code": "BPD_NTBS", "name": "BPD NTBS", "category": "bank"},
    {"code": "BPD_SOUTH_SULAWESI_SELATAN", "name": "BPD SOUTH SULAWESI", "category": "bank"},
    {"code": "BPD_SOUTHEAST_SULAWESI", "name": "BPD SOUTHEAST SULAWESI", "category": "bank"},
    {"code": "BPD_SUMUT_SYARIAH", "name": "BPD SUMUT SYARIAH", "category": "bank"},
    {"code": "BPR_DANAGUNG_ABADI", "name": "DANAGUNG ABADI BPR", "category": "bank"},
    {"code": "BPR_DANAGUNG_BAKTI", "name": "BPR DANAGUNG BAKTI", "category": "bank"},
    {"code": "BPR_DANAGUNG_RAMULTI", "name": "BPR DANAGUNG RAMULTI", "category": "bank"},
    {"code": "BPR_SUPRA", "name": "BPR SUPRA", "category": "bank"},
    {"code": "Bank_Hibank_Indonesia", "name": "PT Bank Hibank Indonesia", "category": "bank"},
    {"code": "TISSUE", "name": "TISSUE", "category": "bank"},
    {"code": "INDONESIA_CCBI", "name": "INDONESIA (CCBI)", "category": "bank"},
    {"code": "PAYPRO", "name": "PAYPRO", "category": "bank"},
    {"code": "pocket", "name": "i.saku", "category": "bank"},
    {"code": "PEARL", "name": "PEARL Bank PEARL", "category": "bank"},
    {"code": "MULTICOLOUR", "name": "MULTICOR Bank MULTICOR", "category": "bank"},
    {"code": "BRK_SYR", "name": "Bank Riau Syariah", "category": "bank"},
    {"code": "CBA", "name": "Commonwealth Bank of Australia", "category": "bank"},
    {"code": "CTBC", "name": "China Trust Commercial Bank, Indonesia Branch", "category": "bank"},
]
