PPAYPROS_PAYOUT_CODES = [
    {"code": "dana", "name": "dana", "category": "wallet"},
    {"code": "gopay", "name": "gopay", "category": "wallet"},
    {"code": "linkaja", "name": "linkaja", "category": "wallet"},
    {"code": "OV", "name": "OVO", "category": "wallet"},
    {"code": "shopeepay", "name": "shopeepay", "category": "wallet"},
    {"code": "ACEH", "name": "BPD ACEH", "category": "bank"},
    {"code": "AGRONIAGA", "name": "BANK AGRO NIAGA", "category": "bank"},
    {"code": "ARTA_NIAGA_KENCANA", "name": "BANK ARTA NIAGA KENCANA", "category": "bank"},
    {"code": "ARTHA", "name": "BANK ARTHA GRAHA", "category": "bank"},
    {"code": "ARTOS", "name": "BANK ARTOS IND", "category": "bank"},
    {"code": "BALI", "name": "BPD BALI", "category": "bank"},
    {"code": "BAML", "name": "BANK OF AMERICA", "category": "bank"},
    {"code": "BANK_ABN", "name": "BANK ABN AMRO", "category": "bank"},
    {"code": "BANK_AKITA", "name": "BANK AKITA", "category": "bank"},
    {"code": "BANK_ANTAR", "name": "BANK ANTARDAERAH", "category": "bank"},
    {"code": "BANK_BUANA", "name": "BANK BUANA IND", "category": "bank"},
    {"code": "BANK_BUMIPUTERA", "name": "BANK BUMIPUTERA", "category": "bank"},
    {"code": "BANK_COMP", "name": "THE BANGKOK BANK COMP. LTD", "category": "bank"},
    {"code": "BANK_C_AGR", "name": "BANK CREDIT AGRICOLE INDOSUEZ", "category": "bank"},
    {"code": "BANK_DANAMON", "name": "KOREA EXCHANGE BANK DANAMON", "category": "bank"},
    {"code": "BANK_EKSEK", "name": "BANK EKSEKUTIF", "category": "bank"},
    {"code": "BANK_FINCONESIA", "name": "BANK FINCONESIA", "category": "bank"},
    {"code": "BANK_HAGA", "name": "BANK HAGA", "category": "bank"},
    {"code": "BANK_HAGAKITA", "name": "BANK HAGAKITA", "category": "bank"},
    {"code": "BANK_HARM", "name": "BANK HARMONI INTERNATIONAL", "category": "bank"},
    {"code": "BANK_HIM", "name": "BANK HIMPUNAN SAUDARA 1906, TBK.", "category": "bank"},
    {"code": "BANK_IFI", "name": "BANK IFI", "category": "bank"},
    {"code": "BANK_INA", "name": "BANK INA PERDANA", "category": "bank"},
    {"code": "BANK_INDOMONEX", "name": "BANK INDOMONEX", "category": "bank"},
    {"code": "BANK_ING", "name": "ING INDONESIA BANK", "category": "bank"},
    {"code": "BANK_JABAR", "name": "BANK JABAR BANTEN", "category": "bank"},
    {"code": "BANK_JATENG", "name": "BANK JATENG", "category": "bank"},
    {"code": "BANK_JATIM", "name": "BANK JATIM", "category": "bank"},
    {"code": "BANK_KEPPEL", "name": "BANK KEPPEL TATLEE BUANA", "category": "bank"},
    {"code": "BANK_LIPPO", "name": "BANK LIPPO", "category": "bank"},
    {"code": "BANK_MAYBANK", "name": "BANK MAYBANK INDOCORP", "category": "bank"},
    {"code": "BANK_MERIN", "name": "BANK MERINCORP", "category": "bank"},
    {"code": "BANK_MITRAN", "name": "BANK MITRANIAGA", "category": "bank"},
    {"code": "BANK_MUL", "name": "BANK MULTICOR TBK.", "category": "bank"},
    {"code": "BANK_NAGARI", "name": "BANK NAGARI", "category": "bank"},
    {"code": "BANK_NOBU", "name": "BANK DIPO INTERNATIONAL", "category": "bank"},
    {"code": "BANK_NTT", "name": "BANK NTT", "category": "bank"},
    {"code": "BANK_PERSY", "name": "BANK PERSYARIKATAN INDONESIA", "category": "bank"},
    {"code": "BANK_SULTRA", "name": "BANK SULTRA", "category": "bank"},
    {"code": "BANK_SWADESI", "name": "BANK SWADESI", "category": "bank"},
    {"code": "BANK_SWAGUNA", "name": "BANK SWAGUNA", "category": "bank"},
    {"code": "BANK_TOKYO", "name": "THE BANK OF TOKYO MITSUBISHI UFJ LTD", "category": "bank"},
    {"code": "BANK_UOB", "name": "BANK UOB INDONESIA", "category": "bank"},
    {"code": "BANK_VICTORIA", "name": "BANK VICTORIA INTERNATIONAL", "category": "bank"},
    {"code": "BANK_WOOR", "name": "BANK WOORI INDONESIA", "category": "bank"},
    {"code": "BANK_YUDHA", "name": "BANK YUDHA BHAKTI", "category": "bank"},
    {"code": "BCA", "name": "BANK BCA", "category": "bank"},
    {"code": "BCA_SYR", "name": "BANK BCA SYARIAH", "category": "bank"},
    {"code": "BENGKULU", "name": "BANK BENGKULU", "category": "bank"},
    {"code": "BISNIS_INTERNASIONAL", "name": "BANK BISNIS INTERNASIONAL", "category": "bank"},
    {"code": "BJB_SYR", "name": "BJB SYARIAH", "category": "bank"},
    {"code": "BNI", "name": "BANK BNI", "category": "bank"},
    {"code": "BNI_SYR", "name": "BANK BNI SYARIAH", "category": "bank"},
    {"code": "BNP_PARIBAS", "name": "BANK BNP PARIBAS INDONESIA", "category": "bank"},
    {"code": "BOC", "name": "BANK OF CHINA LIMITED", "category": "bank"},
    {"code": "BPD_KAITIM", "name": "BPD KALTIM", "category": "bank"},
    {"code": "BPD_KALSEL", "name": "BPD KALSEL", "category": "bank"},
    {"code": "BPD_KALTENG", "name": "BPD KALTENG", "category": "bank"},
    {"code": "BPD_NTB", "name": "BPD NTB", "category": "bank"},
    {"code": "BRI", "name": "BANK BRI", "category": "bank"},
    {"code": "BRI_SYR", "name": "BANK BRI SYARIAH", "category": "bank"},
    {"code": "BTN", "name": "BANK TABUNGAN NEGARA (PERSERO)", "category": "bank"},
    {"code": "BTPN_SYARIAH", "name": "BANK PURBA DANARTA", "category": "bank"},
    {"code": "BUKOPIN", "name": "BANK BUKOPIN", "category": "bank"},
    {"code": "BUMI_ARTA", "name": "BANK BUMI ARTA", "category": "bank"},
    {"code": "CAPITAL", "name": "BANK CAPITAL INDONESIA, TBK.", "category": "bank"},
    {"code": "CCB", "name": "BANK WINDU KENTJANA", "category": "bank"},
    {"code": "CENTRATAMA", "name": "CENTRATAMA NASIONAL BANK", "category": "bank"},
    {"code": "CHINATRUST", "name": "BANK CHINA TRUST INDONESIA", "category": "bank"},
    {"code": "CIMB", "name": "BANK CIMB NIAGA", "category": "bank"},
    {"code": "CITIBANK", "name": "CITIBANK", "category": "bank"},
    {"code": "COMMONWEALTH", "name": "BANK COMMONWEALTH", "category": "bank"},
    {"code": "DAERAH_ISTIMEWA", "name": "BPD DIY", "category": "bank"},
    {"code": "DANAMON", "name": "BANK DANAMON", "category": "bank"},
    {"code": "DBS", "name": "BANK DBS INDONESIA", "category": "bank"},
    {"code": "DEUTSCHE", "name": "DEUTSCHE BANK AG.", "category": "bank"},
    {"code": "DINAR_INDONESIA", "name": "BANK DINAR INDONESIA", "category": "bank"},
    {"code": "DKI", "name": "BANK DKI", "category": "bank"},
    {"code": "EXIMBANK", "name": "BANK EKSPOR INDONESIA", "category": "bank"},
    {"code": "FAMA", "name": "BANK FAMA INTERNASIONAL", "category": "bank"},
    {"code": "FT", "name": "Alfamart", "category": "bank"},
    {"code": "GANESHA", "name": "BANK GANESHA", "category": "bank"},
    {"code": "HANA", "name": "BANK HANA", "category": "bank"},
    {"code": "HARDA_INTERNASIONAL", "name": "BANK HARDA", "category": "bank"},
    {"code": "HSBC", "name": "BANK HSBC", "category": "bank"},
    {"code": "ICBC", "name": "BANK ICBC", "category": "bank"},
    {"code": "INDEX_SELINDO", "name": "BANK INDEX SELINDO", "category": "bank"},
    {"code": "JAMBI", "name": "BPD JAMBI", "category": "bank"},
    {"code": "JASA_JAKARTA", "name": "BANK JASA JAKARTA", "category": "bank"},
    {"code": "JPMORGAN", "name": "JP. MORGAN CHASE BANK", "category": "bank"},
    {"code": "JTRUST", "name": "BANK JTRUST", "category": "bank"},
    {"code": "KALIMANTAN_BARAT", "name": "BPD KALIMANTAN BARAT", "category": "bank"},
    {"code": "KESEJAHTERAAN_EKONOMI", "name": "BANK EKONOMI", "category": "bank"},
    {"code": "LAMPUNG", "name": "BANK LAMPUNG", "category": "bank"},
    {"code": "MALUKU", "name": "BANK MALUKU", "category": "bank"},
    {"code": "MANDIRI", "name": "MANDIRI", "category": "bank"},
    {"code": "MANDIRI_SYR", "name": "BANK SYARIAH MANDIRI", "category": "bank"},
    {"code": "MANDIRI_TASPEN", "name": "BANK SINAR HARAPAN BALI", "category": "bank"},
    {"code": "MASPION", "name": "BANK MASPION", "category": "bank"},
    {"code": "MAYAPADA", "name": "BANK MAYAPADA", "category": "bank"},
    {"code": "MAYBANK", "name": "BANK MAYBANK", "category": "bank"},
    {"code": "MAYORA", "name": "BANK MAYORA", "category": "bank"},
    {"code": "MEGA", "name": "BANK MEGA", "category": "bank"},
    {"code": "MEGA_SYR", "name": "BANK SYARIAH MEGA", "category": "bank"},
    {"code": "MESTIKA_DHARMA", "name": "BANK MESTIKA", "category": "bank"},
    {"code": "MITSUI", "name": "BANK SUMITOMO MITSUI INDONESIA", "category": "bank"},
    {"code": "MIZUHO", "name": "BANK MIZUHO INDONESIA", "category": "bank"},
    {"code": "MUAMALAT", "name": "BANK MUAMALAT", "category": "bank"},
    {"code": "MULTI_ARTA_SENTOSA", "name": "BANK MULTI ARTA SENTOSA", "category": "bank"},
    {"code": "NATIONALNOBU", "name": "BANK NOBU", "category": "bank"},
    {"code": "NUSANTARA_PARAHYANGAN", "name": "BANK NUSANTARA PARAHYANGAN", "category": "bank"},
    {"code": "OCBC", "name": "BANK NISP", "category": "bank"},
    {"code": "OKE", "name": "BANK ANDARA", "category": "bank"},
    {"code": "PANIN", "name": "BANK PANIN", "category": "bank"},
    {"code": "PANIN_SYR", "name": "BANK PANIN DUBAI SYARIAH", "category": "bank"},
    {"code": "PAPUA", "name": "BPD PAPUA", "category": "bank"},
    {"code": "PERMATA", "name": "PERMATA BANK", "category": "bank"},
    {"code": "PRIMA_MASTER", "name": "PRIMA MASTER BANK", "category": "bank"},
    {"code": "QNB_INDONESIA", "name": "BANK KESAWAN", "category": "bank"},
    {"code": "RABOBANK", "name": "RABOBANK INTERNASIONAL INDONESIA", "category": "bank"},
    {"code": "RESONA", "name": "BANK RESONA PERDANIA", "category": "bank"},
    {"code": "RIAU_DAN_KEPRI", "name": "BANK RIAU", "category": "bank"},
    {"code": "ROYAL", "name": "BANK ROYAL INDONESIA", "category": "bank"},
    {"code": "SHINHAN", "name": "BANK METRO EXPRESS", "category": "bank"},
    {"code": "SINARMAS_UUS", "name": "BANK SINARMAS", "category": "bank"},
    {"code": "STANDARD_CHARTERED", "name": "STANDARD CHARTERED BANK", "category": "bank"},
    {"code": "SULAWESI", "name": "BPD SULAWESI TENGAH", "category": "bank"},
    {"code": "SULSELBAR", "name": "BPD SULSEL", "category": "bank"},
    {"code": "SUMSEL_DAN_BABEL", "name": "BANK SUMSEL", "category": "bank"},
    {"code": "SUMUT", "name": "BANK SUMUT", "category": "bank"},
    {"code": "TABUNGAN_PENSIUNAN_NASIONAL", "name": "BANK TABUNGAN PENSIUNAN NASIONAL", "category": "bank"},
    {"code": "ALLO_BANK_INDONESIA", "name": "PT ALLO BANK INDONESIA", "category": "bank"},
    {"code": "BANK_ACEH_SYARIAH", "name": "BANK ACEH SYARIAH", "category": "bank"},
    {"code": "BANK_ALADIN", "name": "BANK ALADIN", "category": "bank"},
    {"code": "BANK_AMAR_INDONESIA", "name": "BANK AMAR INDONESIA", "category": "bank"},
    {"code": "BANK_ANZ", "name": "BANK ANZ", "category": "bank"},
    {"code": "BANK_BANTEN", "name": "BANK BANTEN", "category": "bank"},
    {"code": "BANK_BJB", "name": "BANK BJB", "category": "bank"},
    {"code": "BANK_BPR_KS", "name": "BANK BPR KS", "category": "bank"},
    {"code": "BANK_BTN_SYARIAH", "name": "BANK BTN SYARIAH", "category": "bank"},
    {"code": "BANK_BUKOPIN_SYARIAH", "name": "BANK BUKOPIN SYARIAH", "category": "bank"},
    {"code": "BANK_CHINA_CONSTRUCTION", "name": "PT. BANK CHINA CONSTRUCTION", "category": "bank"},
    {"code": "BANK_CIMB_NIAGA_SYARIAH", "name": "BANK CIMB NIAGA SYARIAH", "category": "bank"},
    {"code": "BANK_DANAMON_SYARIAH", "name": "BANK DANAMON SYARIAH", "category": "bank"},
    {"code": "BANK_DIGITAL_BCA", "name": "BANK DIGITAL BCA", "category": "bank"},
    {"code": "BANK_DKI_SYARIAH", "name": "BANK DKI SYARIAH", "category": "bank"},
    {"code": "BANK_EKA", "name": "BANK EKA", "category": "bank"},
    {"code": "BANK_IBK_INDONESIA", "name": "PT. BANK IBK INDONESIA", "category": "bank"},
    {"code": "BANK_INDEX", "name": "BANK INDEX", "category": "bank"},
    {"code": "BANK_INTERIM_INDONESIA", "name": "BANK INTERIM INDONESIA", "category": "bank"},
    {"code": "BANK_JAGO", "name": "BANK JAGO", "category": "bank"},
    {"code": "BANK_JAGO_UU_SYARIAH", "name": "BANK JAGO UU SYARIAH", "category": "bank"},
    {"code": "BANK_JATENG_SYARIAH", "name": "BANK JATENG SYARIAH", "category": "bank"},
    {"code": "BANK_JATIM_SYARIAH", "name": "BANK JATIM SYARIAH", "category": "bank"},
    {"code": "BANK_JTRUST_INDONESIA", "name": "BANK JTRUST INDONESIA", "category": "bank"},
    {"code": "BANK_KALBAR", "name": "BANK KALBAR", "category": "bank"},
    {"code": "BANK_KALBAR_SYARIAH", "name": "BANK KALBAR SYARIAH", "category": "bank"},
    {"code": "BANK_KALTENG", "name": "BANK KALTENG", "category": "bank"},
    {"code": "BANK_KB_BUKOPIN", "name": "BANK KB BUKOPIN", "category": "bank"},
    {"code": "BANK_KEB_HANA", "name": "BANK KEB HANA", "category": "bank"},
    {"code": "BANK_Krom_Indonesia", "name": "BANK Krom Indonesia", "category": "bank"},
    {"code": "BANK_MAS", "name": "BANK MAS", "category": "bank"},
    {"code": "BANK_MAYBANK_UU_SYARIAH", "name": "BANK MAYBANK UU SYARIAH", "category": "bank"},
    {"code": "BANK_MNC_INTERNASIONAL", "name": "BANK MNC INTERNASIONAL", "category": "bank"},
    {"code": "BANK_NAGARI_SYARIAH", "name": "BANK NAGARI SYARIAH", "category": "bank"},
    {"code": "BANK_NANO_SYARIAH", "name": "PT BANK NANO SYARIAH", "category": "bank"},
    {"code": "BANK_NEO_COMMERCE", "name": "BANK NEO COMMERCE", "category": "bank"},
    {"code": "BANK_OF_CHINA_HKG", "name": "BANK OF CHINA (HKG)", "category": "bank"},
    {"code": "BANK_OF_INDIA_INDONESIA", "name": "BANK OF INDIA INDONESIA", "category": "bank"},
    {"code": "BANK_ONB_INDONESIA", "name": "BANK ONB INDONESIA", "category": "bank"},
    {"code": "BANK_PERMATA_SYARIAH", "name": "BANK PERMATA SYARIAH", "category": "bank"},
    {"code": "BANK_RAYA_INDONESIA", "name": "BANK RAYA INDONESIA", "category": "bank"},
    {"code": "BANK_SAHABAT_SAMPOERNA", "name": "BANK SAHABAT SAMPOERNA", "category": "bank"},
    {"code": "BANK_SBIINDONESIA", "name": "BANK SBIINDONESIA", "category": "bank"},
    {"code": "BANK_SEABANK_INDONESIA", "name": "BANK SEABANK INDONESIA", "category": "bank"},
    {"code": "BANK_SMBC_INDONESIA_TBK", "name": "PT BANK SMBC INDONESIA TBK", "category": "bank"},
    {"code": "BANK_SUMSEL_BABEL_SYARIAH", "name": "BANK SUMSEL BABEL SYARIAH", "category": "bank"},
    {"code": "BANK_SYARIAH_INDONESIA", "name": "BANK SYARIAH INDONESIA", "category": "bank"},
    {"code": "BANK_SulutGo", "name": "BANK SulutGo", "category": "bank"},
    {"code": "BANK_Super_indonesia", "name": "BANK Super indonesia", "category": "bank"},
    {"code": "BANK_VICTORIA_SYARIAH", "name": "BANK VICTORIA SYARIAH", "category": "bank"},
    {"code": "BPD_DIY_SYARIAH", "name": "BPD DIY SYARIAH", "category": "bank"},
    {"code": "BPD_KALSEL_SYARIAH", "name": "BPD KALSEL SYARIAH", "category": "bank"},
    {"code": "BPD_KALTIM_KALTARA", "name": "BPD KALTIM KALTARA", "category": "bank"},
    {"code": "BPD_KALTIM_SYARIAH", "name": "BPD KALTIM SYARIAH", "category": "bank"},
    {"code": "BPD_NTBS", "name": "BPD NTBS", "category": "bank"},
    {"code": "BPD_SULAWESI_SELATAN", "name": "BPD SULAWESI SELATAN", "category": "bank"},
    {"code": "BPD_SULAWESI_TENGGARA", "name": "BPD SULAWESI TENGGARA", "category": "bank"},
    {"code": "BPD_SUMUT_SYARIAH", "name": "BPD SUMUT SYARIAH", "category": "bank"},
    {"code": "BPR_DANAGUNG_ABADI", "name": "BPR DANAGUNG ABADI", "category": "bank"},
    {"code": "BPR_DANAGUNG_BAKTI", "name": "BPR DANAGUNG BAKTI", "category": "bank"},
    {"code": "BPR_DANAGUNG_RAMULTI", "name": "BPR DANAGUNG RAMULTI", "category": "bank"},
    {"code": "BPR_SUPRA", "name": "BPR SUPRA", "category": "bank"},
    {"code": "Bank_Hibank_Indonesia", "name": "PT Bank Hibank Indonesia", "category": "bank"},
    {"code": "DOKU", "name": "DOKU", "category": "bank"},
    {"code": "INDONESIA_CCBI", "name": "INDONESIA(CCBI)", "category": "bank"},
    {"code": "PAYPRO", "name": "PAYPRO", "category": "bank"},
    {"code": "saku", "name": "i.saku", "category": "bank"},
    {"code": "MUTIARA", "name": "MUTIARA Bank MUTIARA", "category": "bank"},
    {"code": "MULTICOR", "name": "MULTICOR Bank MULTICOR", "category": "bank"},
    {"code": "BRK_SYR", "name": "Bank Riau Syariah", "category": "bank"},
    {"code": "CBA", "name": "Commonwealth Bank of Australia", "category": "bank"},
    {"code": "CTBC", "name": "China Trust Commercial Bank, Indonesia Branch", "category": "bank"},
]
