from django.urls import path
from .views import (
    JayapayDepositInitiateView,
    JayapayDepositInitiateDirectMethodView,
    JayapayDepositOrderDetailView,
    JayapayDepositCallbackView,
    JayapayPhDepositInitiateView,
    JayapayPhDepositCallbackView,
    KlikpayDepositInitiateView,
    KlikpayDepositCallbackView,
    AtpayDepositInitiateView,
    AtpayDepositInitiateDirectVAView,
    AtpayDepositCallbackView,
    AtpayDepositQueryView,
    ClientHubDepositInitiateView,
    ClientHubDepositCallbackView,
    SiTransferHubDepositInitiateView,
    SiTransferHubDepositCallbackView,
    PPayProsDepositInitiateView,
    PPayProsDepositInitiateQRView,
    PPayProsDepositCallbackView,
    PPayProsDepositQueryView,
    UsdGatewayDepositInitiateView,
    UsdGatewayDepositCallbackView,
    BankPayDepositInitiateView,
    BankPayDepositInitiateQRView,
    BankPayDepositCallbackView,
    DepositTransactionsListView,
    QRISDepositInitiateView,
    QRISDepositAcceptView,
    QRISDepositRejectView,
)

urlpatterns = [
    path('jayapay/initiate/', JayapayDepositInitiateView.as_view(), name='deposit-jayapay-initiate'),
    path('jayapay/initiate-direct/', JayapayDepositInitiateDirectMethodView.as_view(), name='deposit-jayapay-initiate-direct'),
    path('jayapay/order-detail/', JayapayDepositOrderDetailView.as_view(), name='deposit-jayapay-order-detail'),
    path('jayapay/callback/', JayapayDepositCallbackView.as_view(), name='deposit-jayapay-callback'),
    path('jayapay-ph/initiate/', JayapayPhDepositInitiateView.as_view(), name='deposit-jayapay-ph-initiate'),
    path('jayapay-ph/callback/', JayapayPhDepositCallbackView.as_view(), name='deposit-jayapay-ph-callback'),
    path('klikpay/initiate/', KlikpayDepositInitiateView.as_view(), name='deposit-klikpay-initiate'),
    path('klikpay/callback/', KlikpayDepositCallbackView.as_view(), name='deposit-klikpay-callback'),
    path('atpay/initiate/', AtpayDepositInitiateView.as_view(), name='deposit-atpay-initiate'),
    path('atpay/initiate-va/', AtpayDepositInitiateDirectVAView.as_view(), name='deposit-atpay-initiate-va'),
    path('atpay/callback/', AtpayDepositCallbackView.as_view(), name='deposit-atpay-callback'),
    path('atpay/query/', AtpayDepositQueryView.as_view(), name='deposit-atpay-query'),
    path('clienthub/initiate/', ClientHubDepositInitiateView.as_view(), name='deposit-clienthub-initiate'),
    path('clienthub/callback/', ClientHubDepositCallbackView.as_view(), name='deposit-clienthub-callback'),
    path('sitransferhub/initiate/', SiTransferHubDepositInitiateView.as_view(), name='deposit-sitransferhub-initiate'),
    path('sitransferhub/callback/', SiTransferHubDepositCallbackView.as_view(), name='deposit-sitransferhub-callback'),
    path('ppaypros/initiate/', PPayProsDepositInitiateView.as_view(), name='deposit-ppaypros-initiate'),
    path('ppaypros/initiate-qr/', PPayProsDepositInitiateQRView.as_view(), name='deposit-ppaypros-initiate-qr'),
    path('ppaypros/callback/', PPayProsDepositCallbackView.as_view(), name='deposit-ppaypros-callback'),
    path('ppaypros/query/', PPayProsDepositQueryView.as_view(), name='deposit-ppaypros-query'),
    path('usd/initiate/', UsdGatewayDepositInitiateView.as_view(), name='deposit-usd-initiate'),
    path('usd/callback/', UsdGatewayDepositCallbackView.as_view(), name='deposit-usd-callback'),
    path('usd/callback', UsdGatewayDepositCallbackView.as_view(), name='deposit-usd-callback-noslash'),
    path('bankpay/initiate/', BankPayDepositInitiateView.as_view(), name='deposit-bankpay-initiate'),
    path('bankpay/initiate-qr/', BankPayDepositInitiateQRView.as_view(), name='deposit-bankpay-initiate-qr'),
    path('bankpay/callback/', BankPayDepositCallbackView.as_view(), name='deposit-bankpay-callback'),
    path('qris/initiate/', QRISDepositInitiateView.as_view(), name='deposit-qris-initiate'),
    path('qris/accept/', QRISDepositAcceptView.as_view(), name='deposit-qris-accept'),
    path('qris/reject/', QRISDepositRejectView.as_view(), name='deposit-qris-reject'),
    path('transactions/', DepositTransactionsListView.as_view(), name='deposit-transactions-list'),
]
