# Generated by Django 4.2.7 on 2025-10-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_source', models.CharField(choices=[('balance', 'Balance'), ('balance_deposit', 'Balance Deposit')], max_length=20)),
                ('reward_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('consecutive_bonus_enabled', models.BooleanField(default=False)),
                ('bonus_7_days', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bonus_30_days', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attendance_settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
