# Generated by Django 4.2.7 on 2025-10-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesettings',
            name='rank_rewards',
            field=models.JSONField(blank=True, default=dict, help_text='Mapping: {"1": 5000, "2": 6000, ...}'),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='reward_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('random', 'Random Range'), ('rank', 'Rank Based')], max_length=20),
        ),
    ]
