# Generated by Django 5.0.6 on 2026-01-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0003_attendancesettings_rank_rewards_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesettings",
            name="daily_cycle_days",
            field=models.IntegerField(
                default=7,
                help_text="Number of days in the cycle (e.g. 7). After this day, it loops back to day 1.",
            ),
        ),
        migrations.AddField(
            model_name="attendancesettings",
            name="daily_rewards",
            field=models.JSONField(
                blank=True, default=dict, help_text='Mapping: {"1": 100, "2": 200, ...}'
            ),
        ),
        migrations.AlterField(
            model_name="attendancesettings",
            name="reward_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed Amount"),
                    ("random", "Random Range"),
                    ("rank", "Rank Based"),
                    ("daily", "Daily Sequence"),
                ],
                max_length=20,
            ),
        ),
    ]
