# Generated by Django 4.2.7 on 2025-10-04 20:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_investment', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_limit', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_enabled', models.BooleanField(default=True)),
                ('profit_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('profit_rate', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('profit_method', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], max_length=20)),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('balance_source', models.CharField(choices=[('balance', 'Balance'), ('balance_deposit', 'Balance Deposit')], max_length=20)),
                ('claim_reset_mode', models.CharField(choices=[('at_00', 'Reset at 00:00'), ('after_purchase', 'Reset after purchase duration')], max_length=20)),
                ('claim_reset_hours', models.IntegerField(blank=True, null=True)),
                ('rebate_purchase_levels', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('rebate_profit_levels', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('rebate_settings', models.JSONField(default=dict, help_text='Format: {"purchase": {"level1": 10, "level2": 5}, "profit": {"level1": 8, "level2": 4}}')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('custom_fields', models.JSONField(blank=True, null=True)),
                ('specifications', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_id', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('wallet_type', models.CharField(choices=[('BALANCE', 'Balance'), ('BALANCE_DEPOSIT', 'Balance Deposit')], max_length=20)),
                ('investment_quantity', models.IntegerField(blank=True, null=True)),
                ('commission_level', models.IntegerField(blank=True, null=True)),
                ('voucher_id', models.IntegerField(blank=True, null=True)),
                ('voucher_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.transaction')),
                ('upline_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
