# Generated by Django 4.2.7 on 2025-10-05 05:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('profit_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('profit_method', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], max_length=20)),
                ('claim_reset_mode', models.CharField(choices=[('at_00', 'Reset at 00:00'), ('after_purchase', 'Reset after purchase duration')], max_length=20)),
                ('duration_days', models.IntegerField(help_text='Investment duration in days')),
                ('remaining_days', models.IntegerField(help_text='Days remaining until expiration')),
                ('expires_at', models.DateTimeField(help_text='Investment expiration date')),
                ('last_claim_time', models.DateTimeField(blank=True, null=True)),
                ('next_claim_time', models.DateTimeField(blank=True, null=True)),
                ('total_claimed_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('transaction', models.ForeignKey(help_text='Purchase transaction', on_delete=django.db.models.deletion.CASCADE, to='products.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investments',
                'ordering': ['-created_at'],
            },
        ),
    ]
