# Generated by Django 4.2.7 on 2025-10-05 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_investment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_investment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_investment',
        ),
    ]
