# Generated by Django 4.2.7 on 2025-10-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_max_investment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('PURCHASE_COMMISSION', 'Purchase Commission')], max_length=20),
        ),
    ]
