# Generated by Django 4.2.7 on 2025-10-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_purchase_commission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('PURCHASE_COMMISSION', 'Purchase Commission'), ('PROFIT_COMMISSION', 'Profit Commission')], max_length=20),
        ),
    ]
