# Generated by Django 4.2.7 on 2025-10-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_transaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("CREDIT", "Credit"),
                    ("DEBIT", "Debit"),
                    ("PURCHASE_COMMISSION", "Purchase Commission"),
                    ("PROFIT_COMMISSION", "Profit Commission"),
                    ("EARNED", "Earned"),
                ],
                max_length=20,
            ),
        ),
    ]
