# Generated by Django 4.2.7 on 2025-10-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_add_earned_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("CREDIT", "Credit"),
                    ("DEBIT", "Debit"),
                    ("PURCHASE_COMMISSION", "Purchase Commission"),
                    ("PROFIT_COMMISSION", "Profit Commission"),
                    ("INTEREST", "Interest"),
                ],
                max_length=20,
            ),
        ),
    ]
