# Generated by Django 4.2.7 on 2025-10-25 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0008_remove_earned_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="claims_count",
            field=models.IntegerField(
                default=0, help_text="Total number of claims made"
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="claims_remaining",
            field=models.IntegerField(
                default=0, help_text="Number of claims remaining (calculated field)"
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="first_claim_time",
            field=models.DateTimeField(
                blank=True, help_text="Time of the first claim", null=True
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="last_claim_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount of the last claim",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="total_claimed_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total amount claimed (same as total_claimed_profit)",
                max_digits=15,
            ),
        ),
        migrations.CreateModel(
            name="ClaimHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "claim_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Claim"),
                            ("auto", "Automatic Processing"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("PENDING", "Pending"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                (
                    "claim_number",
                    models.IntegerField(
                        help_text="Sequential claim number for this investment"
                    ),
                ),
                (
                    "remaining_days_at_claim",
                    models.IntegerField(
                        help_text="Remaining days when this claim was made"
                    ),
                ),
                (
                    "total_claimed_before",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount claimed before this claim",
                        max_digits=15,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or error messages"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "investment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_history",
                        to="products.investment",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related profit transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "claim_history",
                "ordering": ["-created_at"],
                "unique_together": {("investment", "claim_number")},
            },
        ),
    ]
