# Generated by Django 4.2.7 on 2025-10-27 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0009_investment_claims_count_investment_claims_remaining_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cashback_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable cashback for this product"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cashback_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cashback percentage (0-100). Example: 10.50 for 10.5%",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
