# Generated by Django 4.2.7 on 2025-10-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_product_cashback_enabled_product_cashback_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("CREDIT", "Credit"),
                    ("DEBIT", "Debit"),
                    ("PURCHASE_COMMISSION", "Purchase Commission"),
                    ("PROFIT_COMMISSION", "Profit Commission"),
                    ("INTEREST", "Interest"),
                    ("INVESTMENTS", "Investments"),
                    ("CASHBACK", "Cashback"),
                ],
                max_length=20,
            ),
        ),
    ]
