# Generated by Django 4.2.7 on 2025-10-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_alter_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="custom_field_10_content",
            field=models.TextField(
                blank=True, help_text="Custom field 10 content", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_10_title",
            field=models.CharField(
                blank=True, help_text="Custom field 10 title", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_1_content",
            field=models.TextField(
                blank=True, help_text="Custom field 1 content", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_1_title",
            field=models.CharField(
                blank=True, help_text="Custom field 1 title", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_2_content",
            field=models.TextField(
                blank=True, help_text="Custom field 2 content", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_2_title",
            field=models.CharField(
                blank=True, help_text="Custom field 2 title", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_3_content",
            field=models.TextField(
                blank=True, help_text="Custom field 3 content", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_3_title",
            field=models.CharField(
                blank=True, help_text="Custom field 3 title", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_4_content",
            field=models.TextField(
                blank=True, help_text="Custom field 4 content", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_4_title",
            field=models.CharField(
                blank=True, help_text="Custom field 4 title", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_5_content",
            field=models.TextField(
                blank=True, help_text="Custom field 5 content", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_5_title",
            field=models.CharField(
                blank=True, help_text="Custom field 5 title", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_6_content",
            field=models.TextField(
                blank=True, help_text="Custom field 6 content", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_6_title",
            field=models.CharField(
                blank=True, help_text="Custom field 6 title", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_7_content",
            field=models.TextField(
                blank=True, help_text="Custom field 7 content", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_7_title",
            field=models.CharField(
                blank=True, help_text="Custom field 7 title", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_8_content",
            field=models.TextField(
                blank=True, help_text="Custom field 8 content", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_8_title",
            field=models.CharField(
                blank=True, help_text="Custom field 8 title", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_9_content",
            field=models.TextField(
                blank=True, help_text="Custom field 9 content", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_field_9_title",
            field=models.CharField(
                blank=True, help_text="Custom field 9 title", max_length=255, null=True
            ),
        ),
    ]
