# Generated by Django 4.2.7 on 2025-11-01 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_product_custom_field_10_content_and_more"),
    ]

    operations = []
