# Generated by Django 4.2.7 on 2025-11-01 16:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0013_change_image_field_to_imagefield"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="max_purchase_count",
            field=models.IntegerField(
                default=3,
                help_text="Maximum number of times a user can purchase this product (default: 3)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.CreateModel(
            name="UserProductPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times user has purchased this product",
                    ),
                ),
                (
                    "first_purchase_date",
                    models.DateTimeField(
                        blank=True, help_text="Date of first purchase", null=True
                    ),
                ),
                (
                    "last_purchase_date",
                    models.DateTimeField(
                        blank=True, help_text="Date of last purchase", null=True
                    ),
                ),
                (
                    "cashback_claimed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user has claimed cashback for this product",
                    ),
                ),
                (
                    "cashback_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total cashback amount received for this product",
                        max_digits=15,
                    ),
                ),
                (
                    "cashback_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when cashback was claimed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_product_purchases",
                "ordering": ["-updated_at"],
                "unique_together": {("user", "product")},
            },
        ),
    ]
