# Generated by Django 4.2.7 on 2025-11-04 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_product_max_purchase_count_userproductpurchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="claim_reset_mode",
            field=models.CharField(
                choices=[
                    ("at_00", "Reset at 00:00"),
                    ("after_purchase", "Reset after purchase duration"),
                ],
                default="after_purchase",
                max_length=20,
            ),
        ),
    ]
