# Generated by Django 4.2.13 on 2025-11-09 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_product_custom_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='custom_fields',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rebate_profit_levels',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rebate_purchase_levels',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rebate_settings',
        ),
        migrations.AddField(
            model_name='product',
            name='profit_rebate_level_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='profit_rebate_level_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='profit_rebate_level_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='profit_rebate_level_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='profit_rebate_level_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_rebate_level_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_rebate_level_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_rebate_level_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_rebate_level_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_rebate_level_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_purchase_count',
            field=models.IntegerField(default=3, help_text='Maximum number of times a user can purchase this product', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('PURCHASE_COMMISSION', 'Purchase Commission'), ('PROFIT_COMMISSION', 'Profit Commission'), ('INTEREST', 'Interest'), ('INVESTMENTS', 'Investments'), ('CASHBACK', 'Cashback'), ('REJECT', 'Reject')], max_length=20),
        ),
        migrations.DeleteModel(
            name='UserProductPurchase',
        ),
    ]
