# Generated by Django 5.0.6 on 2025-11-21 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_product_require_upline_ownership_for_commissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="profit_random_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="profit_random_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="profit_random_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="profit_random_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="profit_type",
            field=models.CharField(
                choices=[
                    ("percentage", "Percentage"),
                    ("fixed", "Fixed Amount"),
                    ("random", "Random Range"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="profit_type",
            field=models.CharField(
                choices=[
                    ("percentage", "Percentage"),
                    ("fixed", "Fixed Amount"),
                    ("random", "Random Range"),
                ],
                max_length=20,
            ),
        ),
    ]
