# Generated by Django 5.0.6 on 2025-12-08 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0020_alter_product_price_alter_product_profit_random_max_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="profit_random_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="profit_random_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="profit_rate",
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name="product",
            name="profit_rate",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
