# Generated by Django 5.0.6 on 2026-01-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0021_alter_investment_profit_random_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="claim_reset_mode",
            field=models.CharField(
                choices=[
                    ("at_00", "Reset at 00:00"),
                    ("at_custom", "Reset at Custom Hour (Daily)"),
                    ("after_purchase", "Reset after purchase duration"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="claim_reset_mode",
            field=models.CharField(
                choices=[
                    ("at_00", "Reset at 00:00"),
                    ("at_custom", "Reset at Custom Hour (Daily)"),
                    ("after_purchase", "Reset after purchase duration"),
                ],
                default="after_purchase",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("CREDIT", "Credit"),
                    ("BONUS", "Bonus"),
                    ("DEBIT", "Debit"),
                    ("PURCHASE_COMMISSION", "Purchase Commission"),
                    ("PROFIT_COMMISSION", "Profit Commission"),
                    ("INTEREST", "Interest"),
                    ("INVESTMENTS", "Investments"),
                    ("CASHBACK", "Cashback"),
                    ("REJECT", "Reject"),
                ],
                max_length=20,
            ),
        ),
    ]
