# Generated by Django 5.0.6 on 2026-02-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0022_alter_investment_claim_reset_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="principal_returned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="return_principal_on_completion",
            field=models.BooleanField(default=False),
        ),
    ]
