# Generated by Django 5.0.6 on 2026-02-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0023_investment_principal_returned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("CREDIT", "Credit"),
                    ("BONUS", "Bonus"),
                    ("DEBIT", "Debit"),
                    ("PURCHASE_COMMISSION", "Purchase Commission"),
                    ("PROFIT_COMMISSION", "Profit Commission"),
                    ("INTEREST", "Interest"),
                    ("INVESTMENTS", "Investments"),
                    ("CASHBACK", "Cashback"),
                    ("REJECT", "Reject"),
                    ("RETURN", "Return"),
                ],
                max_length=20,
            ),
        ),
    ]
