# Generated by Django 5.0.6 on 2026-03-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0026_product_rank_requirements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="profit_method",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("auto", "Automatic"),
                    ("hold", "Hold Until Maturity"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("CREDIT", "Credit"),
                    ("BONUS", "Bonus"),
                    ("DEBIT", "Debit"),
                    ("PURCHASE_COMMISSION", "Purchase Commission"),
                    ("PROFIT_COMMISSION", "Profit Commission"),
                    ("INTEREST", "Interest"),
                    ("INVESTMENTS", "Investments"),
                    ("CASHBACK", "Cashback"),
                    ("REJECT", "Reject"),
                    ("RETURN", "Return"),
                    ("HOLD_RELEASE", "Hold Release"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="wallet_type",
            field=models.CharField(
                choices=[
                    ("BALANCE", "Balance"),
                    ("BALANCE_DEPOSIT", "Balance Deposit"),
                    ("BALANCE_HOLD", "Balance Hold"),
                ],
                max_length=20,
            ),
        ),
    ]
