# Generated by Django 5.0.6 on 2026-05-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0033_product_required_golongan"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="currency_code",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="original_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="original_currency_code",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="conversion_rate_to_idr",
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]

