# Generated by Django 4.2.13 on 2026-05-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_transaction_currency_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='conversion_rate_to_idr',
            new_name='conversion_rate',
        ),
    ]
