# Generated by ChatGPT on 2026-06-26
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0037_product_require_withdraw_pin_on_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("CREDIT", "Credit"),
                    ("BONUS", "Bonus"),
                    ("DEBIT", "Debit"),
                    ("TRANSFER", "Transfer"),
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAW", "Withdraw"),
                    ("PURCHASE_COMMISSION", "Purchase Commission"),
                    ("PROFIT_COMMISSION", "Profit Commission"),
                    ("INTEREST", "Interest"),
                    ("INVESTMENTS", "Investments"),
                    ("MISSIONS", "Missions"),
                    ("VOUCHER", "Voucher"),
                    ("ATTENDANCE", "Attendance"),
                    ("CASHBACK", "Cashback"),
                    ("CASHBACK_DEPOSIT", "Cashback Deposit"),
                    ("REJECT", "Reject"),
                    ("RETURN", "Return"),
                    ("HOLD_RELEASE", "Hold Release"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="wallet_type",
            field=models.CharField(
                choices=[
                    ("BALANCE", "Balance"),
                    ("BALANCE_DEPOSIT", "Balance Deposit"),
                    ("BALANCE_HOLD", "Balance Hold"),
                    ("BALANCE_CASHBACK", "Balance Cashback"),
                ],
                max_length=20,
            ),
        ),
    ]

