# Generated by Django 4.2.13 on 2026-07-14 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_voucher_is_daily_claim'),
        ('products', '0039_fix_return_transaction_amount_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='voucher_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.voucher'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Conversion rate'),
        ),
    ]
