# Generated by Django 4.2.13 on 2026-07-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_remove_transaction_voucher_id_transaction_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='claim_reset_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
