# Generated by Django 4.2.7 on 2025-10-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalsettings',
            name='balance_source',
            field=models.CharField(choices=[('balance', 'Balance'), ('balance_deposit', 'Balance Deposit')], default='balance', max_length=20),
        ),
    ]
