# Generated by Django 4.2.7 on 2025-10-05 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_transaction_status'),
        ('withdrawal', '0002_withdrawalsettings_balance_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_withdrawal', to='products.transaction'),
        ),
    ]
