# Generated by Django 4.2.7 on 2025-10-27 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("withdrawal", "0003_withdrawal_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalJayapay",
            fields=[],
            options={
                "verbose_name": "Withdrawal Jayapay",
                "verbose_name_plural": "Withdrawals Jayapay",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("withdrawal.withdrawal",),
        ),
    ]
