# Generated by Django 4.2.13 on 2025-11-10 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0004_withdrawaljayapay'),
    ]

    operations = [
        migrations.CreateModel(
            name='JayapayWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_params', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('withdrawal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jayapay_withdrawal', to='withdrawal.withdrawal')),
            ],
            options={
                'db_table': 'withdrawal_jayapay',
                'ordering': ['-created_at'],
            },
        ),
    ]
