# Generated by Django 4.2.13 on 2025-11-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("withdrawal", "0005_jayapaywithdrawal"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalsettings",
            name="require_pin",
            field=models.BooleanField(default=False),
        ),
    ]
