# Generated by Django 4.2.13 on 2025-12-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0006_withdrawalsettings_require_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalsettings',
            name='require_active_investment',
            field=models.BooleanField(default=False, help_text='User must have at least one active investment to withdraw'),
        ),
    ]
