# Generated by Django 5.0.6 on 2026-02-16 07:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("withdrawal", "0007_withdrawalsettings_require_active_investment"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("duration_hours", models.PositiveIntegerField()),
                (
                    "fee_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "withdrawal_services",
                "ordering": ["sort_order", "duration_hours", "name"],
            },
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="withdrawal_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="withdrawals",
                to="withdrawal.withdrawalservice",
            ),
        ),
    ]
