# Generated by Django 5.0.6 on 2026-05-16 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("withdrawal", "0011_withdrawalservice_fee_fixed"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsdPayoutWithdrawal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_params", models.JSONField(default=dict)),
                ("response_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "withdrawal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usd_payout_withdrawal",
                        to="withdrawal.withdrawal",
                    ),
                ),
            ],
            options={
                "db_table": "withdrawal_usd_payout",
                "ordering": ["-created_at"],
            },
        ),
    ]

