# Generated by Django 5.0.6 on 2026-05-23 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("withdrawal", "0012_usdpayoutwithdrawal"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY (c.conkey)
        WHERE t.relname = 'withdrawals'
          AND c.contype IN ('p', 'u')
          AND a.attname = 'id'
          AND array_length(c.conkey, 1) = 1
    ) THEN
        ALTER TABLE public.withdrawals ADD CONSTRAINT withdrawals_id_uniq UNIQUE (id);
    END IF;
END $$;
""",
            reverse_sql="""
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'withdrawals_id_uniq') THEN
        ALTER TABLE public.withdrawals DROP CONSTRAINT withdrawals_id_uniq;
    END IF;
END $$;
""",
        ),
        migrations.AddField(
            model_name="withdrawalsettings",
            name="app_domain",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Contoh: myapp.example.com (tanpa http/https)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="withdrawalsettings",
            name="jayapay_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="withdrawalsettings",
            name="jayapay_merchant_code",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="withdrawalsettings",
            name="jayapay_private_key",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Paste RSA PRIVATE KEY body ONLY (without BEGIN/END headers)",
            ),
        ),
        migrations.AddField(
            model_name="withdrawalsettings",
            name="jayapay_public_key",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional: PUBLIC KEY untuk verifikasi/dekripsi callback bila diperlukan",
            ),
        ),
        migrations.AddField(
            model_name="withdrawalsettings",
            name="jayapay_ph_payout_api_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="withdrawalsettings",
            name="jayapay_ph_payout_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="withdrawalsettings",
            name="jayapay_ph_payout_fee_type",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="0: fee deduct in order; 1: handling fee calculated separately",
            ),
        ),
        migrations.AddField(
            model_name="withdrawalsettings",
            name="jayapay_ph_payout_mch_no",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="withdrawalsettings",
            name="jayapay_ph_payout_private_key",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Paste RSA PRIVATE KEY body ONLY (without BEGIN/END headers)",
            ),
        ),
        migrations.AddField(
            model_name="withdrawalsettings",
            name="jayapay_ph_payout_public_key",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional: Platform PUBLIC KEY untuk verifikasi callback",
            ),
        ),
        migrations.CreateModel(
            name="JayapayPhPayoutWithdrawal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_params", models.JSONField(default=dict)),
                ("response_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "withdrawal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jayapay_ph_payout_withdrawal",
                        to="withdrawal.withdrawal",
                    ),
                ),
            ],
            options={
                "db_table": "withdrawal_jayapay_ph_payout",
                "ordering": ["-created_at"],
            },
        ),
    ]
