# Generated by Django 4.2.13 on 2026-08-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0016_atpay_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalsettings',
            name='bankpay_payout_api_url',
            field=models.CharField(blank=True, default='https://pay.bankpay.cfd', max_length=255),
        ),
        migrations.AddField(
            model_name='withdrawalsettings',
            name='bankpay_payout_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawalsettings',
            name='bankpay_payout_key',
            field=models.CharField(blank=True, default='', help_text='MERCHANT_KEY untuk signature MD5 payout', max_length=255),
        ),
        migrations.AddField(
            model_name='withdrawalsettings',
            name='bankpay_payout_member_id',
            field=models.CharField(blank=True, default='', help_text='Merchant ID dari BankPay', max_length=100),
        ),
        migrations.CreateModel(
            name='BankPayWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_params', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('withdrawal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bankpay_withdrawal', to='withdrawal.withdrawal')),
            ],
            options={
                'db_table': 'withdrawal_bankpay',
                'ordering': ['-created_at'],
            },
        ),
    ]
