# Generated by Django 4.2.13 on 2026-08-30 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0018_reepay_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalsettings',
            name='batpay_payout_api_key',
            field=models.CharField(blank=True, default='', help_text='X-API-Key merchant (ak_...)', max_length=255),
        ),
        migrations.AddField(
            model_name='withdrawalsettings',
            name='batpay_payout_api_url',
            field=models.CharField(blank=True, default='https://api.wayrooou.online', help_text='Base URL BatPay', max_length=255),
        ),
        migrations.AddField(
            model_name='withdrawalsettings',
            name='batpay_payout_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawalsettings',
            name='batpay_payout_secret_key',
            field=models.TextField(blank=True, default='', help_text='Secret key HMAC-SHA256 payout (347 karakter - jangan VARCHAR(255))'),
        ),
        migrations.CreateModel(
            name='BatPayWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_params', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('withdrawal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batpay_withdrawal', to='withdrawal.withdrawal')),
            ],
            options={
                'db_table': 'withdrawal_batpay',
                'ordering': ['-created_at'],
            },
        ),
    ]
